---
title: "DE_per_time"
author: "Sarah Hazell Pickering"
date: "2025-02-11"
output: html_document
---


beige_vs_white DEGs at day1 and day3. 

```{r libs, message=FALSE, warning=FALSE}
library(BPCells)
library(Seurat)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(here)
library(tidyr)
```


```{r params}
module = "beige_vs_white"
dataname = "downsample"
load_data = T #loading data
subset_data = F

rmd_filename = "beige_vs_white_downsample_DE_per_cluster"
i_am(file.path("analysis", module, paste0(rmd_filename,".Rmd")))
odir = here("output", module, dataname)

```


```{r setup}
set.seed(8)
fig_dir = here("analysis", module, "figures", rmd_filename)
if (!dir.exists(fig_dir)) dir.create(fig_dir, recursive = TRUE)
knitr::opts_chunk$set(fig.path = paste0(fig_dir, "/"),
                      dev = c("png","pdf"))

if (!dir.exists(odir)) dir.create(odir, recursive = TRUE)
```


```{r themes}
theme_hp = theme_classic(base_size = 15) +
  theme(axis.line = element_line(linewidth = 0.25),
        axis.ticks = element_line(linewidth = 0.25),
        strip.background = element_blank())
theme_set(theme_hp)
pal = c("#1F78B4","#85C2EA","#B3B3B3", "#F18486", "#E31A1C")
clusters =   tvthemes::gravityFalls_pal()(13)
spectral = rev(RColorBrewer::brewer.pal(n = 11, name = 'Spectral'))
```

## Read data

```{r}
if (subset_data){
  sbs = readRDS(here(odir, "10%_complete_analysis.rds"))
} else {
  sbs = readRDS(here(odir, "complete_analysis.rds"))
  DefaultAssay(sbs) = "RNA"
}
Idents(sbs) = "cond.time"
sbs
table(Idents(sbs))
```

```{r}
DimPlot(sbs, cols= pal, shuffle=T)
```

## Day3
```{r}
day3_test = FindMarkers(sbs, ident.1="beige.day3",ident.2="white.day3")
day3_test = mutate(day3_test, sig=if_else(p_val_adj < 0.01 & 
         (pct.1 + pct.2) > 0.2 & abs(avg_log2FC) > 0.25,"sig","not_sig"), 
         condition = if_else(avg_log2FC > 0, "beige", "white"),
         sig_cond = if_else(sig == "not_sig", "not_sig",
                            if_else(avg_log2FC > 0, "beige", "white")
                            ),
         gene_name = row.names(day3_test))%>%
  arrange(sig == "not_sig", desc(abs(avg_log2FC)))
table(day3_test$sig_cond)
head(day3_test, n=20)
```


```{r day3_volcano}
ggplot(day3_test, aes(x=avg_log2FC, y=-log10(p_val), colour=sig_cond)) + geom_point(size=0.5) + 
  geom_text_repel(data = slice_min(day3_test, n=20, order_by = p_val), aes(label=gene_name), show.legend = F) + 
  scale_colour_manual(values=c(pal[5],"black",pal[1])) + guides(colour = guide_legend(override.aes = list(size = 2)))  +
  ggtitle("day3") + coord_cartesian(x=c(-1,1))

ggplot(day3_test, aes(x=avg_log2FC, y=-log10(p_val), colour=sig_cond)) + geom_point(size=0.5) + 
  geom_text_repel(data = slice_min(day3_test, n=70, order_by = p_val), aes(label=gene_name)) + 
  scale_colour_manual(values=c(pal[5],"black",pal[1])) + guides(colour = guide_legend(override.aes = list(size = 2))) +
  ggtitle("day3 zoom") + coord_cartesian(x=c(-1,1), y=c(0, 100)) 
```




## day 1
```{r}
day1_test = FindMarkers(sbs, ident.1="beige.day1",ident.2="white.day1")
day1_test = mutate(day1_test, sig=if_else(p_val_adj < 0.01 & 
         (pct.1 + pct.2) > 0.2 & abs(avg_log2FC) > 0.25,"sig","not_sig"), 
         condition = if_else(avg_log2FC > 0, "beige", "white"),
         sig_cond = if_else(sig == "not_sig", "not_sig",
                            if_else(avg_log2FC > 0, "beige", "white")
                            ),
         gene_name = row.names(day1_test)) %>%
  arrange(sig == "not_sig", desc(abs(avg_log2FC)))
table(day1_test$sig_cond)
head(day1_test, n=20)
```



```{r day1_volcano}
ggplot(day1_test, aes(x=avg_log2FC, y=-log10(p_val), colour=sig_cond)) + geom_point(size=0.5) + 
  geom_text_repel(data = slice_min(day1_test, n=20, order_by = p_val), aes(label=gene_name)) + 
  scale_colour_manual(values=c(pal[4],"black",pal[2]))+ guides(colour = guide_legend(override.aes = list(size = 2))) +
  ggtitle("day1")+ coord_cartesian(x=c(-1,1))

ggplot(day1_test, aes(x=avg_log2FC, y=-log10(p_val), colour=sig_cond)) + geom_point(size=0.5) + 
  geom_text_repel(data = slice_min(day1_test, n=70, order_by = p_val), aes(label=gene_name)) + 
  scale_colour_manual(values=c(pal[4],"black",pal[2])) + guides(colour = guide_legend(override.aes = list(size = 2))) +
  ggtitle("day1 zoom") + coord_cartesian(x=c(-1,1), y=c(0, 100))
```


## Save tables
```{r}
if (subset_data == F){
  write.table(filter(day3_test, p_val_adj < 0.01), here(odir, "DE_day3_wvb.tsv"),
              sep="\t",row.names = F, quote = F)
  write.table(filter(day1_test, p_val_adj < 0.01), here(odir, "DE_day1_wvb.tsv"),
              sep="\t",row.names = F, quote = F)
}
```

