---
title: "bvw_fastmnn_combine_pseudotime"
author: "Sarah Hazell Pickering"
date: "2026-02-10"
output: html_document
---

# Setup

```{r libs, message=FALSE, warning=FALSE}
library(BPCells)
library(Seurat)
library(dplyr)
library(ggplot2)
library(here)
library(monocle3)
library(viridis)
```

```{r params}
module = "beige_vs_white"
method_name = "fastmnn"
dataname = paste0("bvw_",method_name)
load_data = T #loading data
subset_data = F

rmd_filename = "bvw_fastmnn_monocle_umap_plots"
i_am(file.path("analysis", module, paste0(rmd_filename,".Rmd")))
odir = here("output", module, dataname)
```

```{r setup}
set.seed(8)
fig_dir = here("analysis", module, "figures", rmd_filename)
if (!dir.exists(fig_dir)) dir.create(fig_dir, recursive = TRUE)
knitr::opts_chunk$set(fig.path = paste0(fig_dir, "/"),
                      dev = c("png","pdf"))

if (!dir.exists(odir)) dir.create(odir, recursive = TRUE)
```

```{r themes}
theme_hp = theme_classic(base_size = 15) +
  theme(axis.line = element_line(linewidth = 0.25),
        axis.ticks = element_line(linewidth = 0.25),
        strip.background = element_blank())
theme_set(theme_hp)

pal_white = c("#B3B3B3","#85C2EA","#1F78B4")
names(pal_white) = c("day0","day1","day3")
pal_beige = c("#B3B3B3", "#F18486","#E31A1C")
names(pal_beige) = c("day0","day1","day3")
pal = c("#1F78B4","#85C2EA","#B3B3B3", "#F18486","#E31A1C")

prog_cols = c("#DA1819","#691A93","#EBB400" , "#434D51","#00AED1","#3AAD00","#FF7F00")
prog_levels = c("p5","p4","p6","p3","p0","p1","p2")
names(prog_cols) = paste0("p", 0:(length(prog_levels)-1))
clusters = MetBrewer::met.brewer("Redon", 12)
names(clusters) = 0:11
spectral = rev(RColorBrewer::brewer.pal(n = 11, name = 'Spectral'))
```

# Monocle3
## load data
```{r}
beige =  readRDS(here(odir,"beige_monocle_complete_analysis_umap.rds"))
white = readRDS(here(odir,"white_monocle_complete_analysis_umap.rds"))
beige
colnames(colData(beige))
```

## Beige Trajectory

```{r}
table(beige$time.progen_clusters)
table(beige$progen_clusters,useNA="ifany")
beige$only_progen_clusters = beige$progen_clusters
beige$progen_clusters = beige$time.progen_clusters
```

```{r beige_trajectories}
p=plot_cells(beige, color_cells_by = "progen_clusters", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F,  cell_size=0.5)+
  scale_colour_manual(values=c(prog_cols, pal_beige))
p$layers[[1]]$aes_params$colour = 'transparent' 
p 


p=plot_cells(beige, color_cells_by = "progen_clusters", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F,  cell_size=0.2)+
  scale_colour_manual(values=c(prog_cols, pal_beige))
p$layers[[1]]$aes_params$colour = 'transparent'
p + facet_wrap(~ time.progen_clusters)
```

## white trajectory

```{r}
white$only_progen_clusters = white$progen_clusters
white$progen_clusters = white$time.progen_clusters
```

```{r white_trajectories}
w=plot_cells(white, color_cells_by = "progen_clusters", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F,  cell_size=0.5) +
  scale_colour_manual(values=c(prog_cols, pal_white),name = "cluster")
w$layers[[1]]$aes_params$colour = 'transparent'
w


w=plot_cells(white, color_cells_by = "progen_clusters", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F, cell_size=0.2) +
  scale_colour_manual(values=c(prog_cols, pal_white),name = "cluster")
w$layers[[1]]$aes_params$colour = 'transparent'
w + facet_wrap(~ progen_clusters)
```

```{r white_prog_trajectories}
white_progen = white[,subset(colData(white), grepl("^p[0-7]",time.progen_clusters)) %>%row.names]
w=plot_cells(white_progen, color_cells_by = "progen_clusters", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F, cell_size=0.2)
w$layers[[1]]$aes_params$colour = 'transparent'
w + facet_wrap(~ progen_clusters) +
  scale_colour_manual(values=c(prog_cols, pal_white),name = "cluster")
```
## Only trajectory plots
```{r only_graph_white}
plot_cells(white, label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F, cell_size=0,
            graph_label_size = 5) 

plot_cells(white, label_leaves = F, label_branch_points = F, 
                trajectory_graph_color=pal[1], label_cell_groups = F, cell_size=0,
            graph_label_size = 5) 
```

```{r only_graph_beige}
plot_cells(beige, label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F, cell_size=0,
            graph_label_size = 5)

plot_cells(beige, label_leaves = F, label_branch_points = F, 
                trajectory_graph_color=pal[5], label_cell_groups = F, cell_size=0, 
           graph_label_size = 5)
```

## Add pseudotime to seurat objects

```{r}
if (subset_data){
  sbs = readRDS(here(odir, "10%_complete_analysis.rds"))
  Idents(sbs) = "seurat_clusters"
} else {
  sbs = readRDS(here(odir, "complete_analysis.rds"))
  DefaultAssay(sbs) = "RNA"
}
sbs
```

```{r}
Idents(sbs) = "cond.time"
sbs_white = subset(sbs, idents=c("asc.day0", "white.day1","white.day3"))
colnames_white = colnames(white) == rownames(sbs_white@meta.data)

sbs_beige = subset(sbs, idents=c("asc.day0", "beige.day1","beige.day3"))
colnames_beige = colnames(beige) == rownames(sbs_beige@meta.data)
if (!all(c(colnames_white, colnames_beige))){
    cat("white cell matches:\n")
    cat(summary(colnames_white))
    cat("\nbeige cell matches:\n")
    cat(colnames_beige)
    stop("Error: Cell ids do not match for monocle and seurat objects")
} else {
    sbs_white$raw_pseudotime = pseudotime(white)
    sbs_white$monocle_pseudotime =   scales::rescale(pseudotime(white), to = c(1, 0)) #rescale from 1 to 0 (cos were tracing backwards from  day3)
    sbs_white$pscondition ="white"
    
    sbs_beige$raw_pseudotime = pseudotime(beige)
    sbs_beige$monocle_pseudotime =   scales::rescale(sbs_beige$raw_pseudotime, to = c(1, 0)) #rescale from 1 to 0 (cos were tracing backwards from  day3)
    sbs_beige$pscondition ="beige"
}
```

### Rm monocle objects

Already covered by monocle 
```{r}
rm(white, beige)
```

# Velocity pseudotime

```{r}
if (subset_data){
  #white = readRDS(here(odir,"10%_dynamical_velocity_scexperiment_white.rds"))
  #beige = readRDS(here(odir,"10%_dynamical_velocity_scexperiment_beige.rds"))
    total = readRDS(here(odir,"10%_dynamical_velocity_scexperiment.rds"))
} else {
  # white = readRDS(here(odir,"dynamical_velocity_scexperiment_white.rds"))
  # beige = readRDS(here(odir,"dynamical_velocity_scexperiment_beige.rds"))
    total = readRDS(here(odir,"dynamical_velocity_scexperiment.rds"))
}
# white
# beige
total
```

```{r}
add_pseudotime = function(seurat, velocity, condition_col="velocity"){
    pseudotime_vals <- rep(NA, length = length(colnames(seurat)))
    names(pseudotime_vals) <- colnames(seurat)
    existing_cells <- intersect(colnames(seurat), colnames(velocity))
    pseudotime_vals[existing_cells] <- colData(velocity)[existing_cells,'velocity_pseudotime']
    print(summary(pseudotime_vals))
    seurat$velocity_pseudotime <- pseudotime_vals
    seurat$pscondition = condition_col
    return(seurat)
}

#sbs_white = add_pseudotime(sbs_white, white, condition_col="white")
#sbs_beige = add_pseudotime(sbs_beige, beige, condition_col="beige")
sbs = add_pseudotime(sbs, total)
summary(is.na(sbs$velocity_pseudotime))
filt = subset(sbs, cells=WhichCells(sbs, expression=velocity_pseudotime >0))
filt
```


```{r tsne_velocity_pseudotime}
# FeaturePlot(sbs_white, "velocity_pseudotime",pt.size = 0.5)+ scale_colour_viridis(direction=-1)
# FeaturePlot(sbs_beige, "velocity_pseudotime",pt.size = 0.5)+ scale_colour_viridis(direction=-1)
FeaturePlot(filt, "velocity_pseudotime",pt.size = 0.5)+ scale_colour_viridis(direction=-1)
```

## Merge white and beige objects
```{r }
merged_obj <- merge(x = sbs_white, y = sbs_beige, add.cell.ids = c("white","beige"), merge.dr = F)
merged_obj
merged_obj$progen_clusters = factor(merged_obj$progen_clusters, levels=c(paste0("p",0:7),paste0("day",c(0,1,3))))
head(merged_obj@meta.data)
```


## Violin plots
```{r paired_ridge_plot}
VlnPlot(merged_obj, features = "monocle_pseudotime", group.by = "time.progen_clusters", split.by="pscondition",
        cols= c("#FF7F00",  "#1F78B4"), pt.size = 0, split.plot = T) + coord_flip() +
  scale_x_discrete(limits = rev(c(prog_levels, paste0("day",c(1,3))))) +
  labs(x="Progenitor cluster // time", y="Monocle Pseudotime", title=NULL) + guides(fill=guide_legend(reverse=T))
```

```{r}
VlnPlot(filt, features = "velocity_pseudotime", group.by = "time.progen_clusters", cols=c(prog_cols, pal_beige), pt.size = 0) +
  scale_x_discrete(limits=c(prog_levels, paste0("day",c(1,3))))
```

```{r}
meta_white = sbs_white@meta.data %>% mutate(pscondition = "white")
meta_beige = sbs_beige@meta.data %>% mutate(pscondition = "beige")
meta = rbind(meta_white, meta_beige)
meta  = mutate(meta, sample_or_progen_cluster = 
                    if_else(time.progen_clusters %in% c("day1","day3"), 
                            meta$cond.time,  
                            time.progen_clusters))
meta$sample_or_progen_cluster = factor(meta$sample_or_progen_cluster, 
                                       levels=c(prog_levels, c("day0","white.day1", "beige.day1","white.day3","beige.day3")))
str(meta)
table(meta$pscondition)
table(meta$sample_or_progen_cluster)
```


## Save

save for g2g_alignment
```{r}
if (subset_data){
    write.table(meta, file =here(odir,"10%_combined_pseudotime.tsv"), sep="\t", row.names = F, quote=F)
    saveRDS(sbs_white, file=here(odir, "10%_white_combined_pseudotime_seurat.rds"))
    saveRDS(sbs_beige, file=here(odir, "10%_beige_combined_pseudotime_seurat.rds"))
} else if (!subset_data){
    write.table(meta, here(odir,"combined_pseudotime.tsv"), sep="\t", row.names = F, quote=F)
    saveRDS(sbs_white, file=here(odir, "white_combined_pseudotime_seurat.rds"))
    saveRDS(sbs_beige, file=here(odir, "beige_combined_pseudotime_seurat.rds"))
    saveRDS(filt, file=here(odir, "combined_pseudotime_seurat.rds"))
}

```
