---
title: "marker_gene_ontologies"
author: "Sarah Hazell Pickering"
date: "2024-08-07"
output: html_document
---

```{r}
module = "progenitors"
dataname = "initial"
library(here); i_am(file.path("analysis",module, "marker_gene_ontologies.Rmd"))
indir = here("data/cellranger/count_no_introns/day0")
odir = here("output", module, dataname) 
dataname = "initial"

if (!dir.exists(odir)){dir.create(odir, recursive = T)}
```

Default load=T and subset=F because its just marker genes.  

```{r message=FALSE, warning=FALSE, echo=TRUE}
library(clusterProfiler, quietly = T)
library(enrichplot)
library(dplyr)
library(ggplot2)
```

```{r colours}
pal = c("#DA1819", "#00AED1", "#434D51","#EBB400","#691A93","#3AAD00")
clusters = c("#FED439FF", "#709AE1FF", "#8A9197FF", "#D2AF81FF",
             "#FD7446FF", "#D5E4A2FF", "#197EC0FF", "#46732EFF", "#71D0F5FF")
``` 

## Load marker lists
```{r}
cluster.markers = read.delim(here(odir, "marker_genes.txt"))
cluster.markers = filter(cluster.markers, p_val_adj < 0.01)
all.genes = read.delim(here("data", "all.genes.txt"))[,1]
head(all.genes); length(all.genes)
donor.markers = read.delim(here(odir, "donor_marker_genes.txt"))
donor.markers = filter(donor.markers, p_val_adj < 0.01)
```


### GO setup
```{r}
molsig <- clusterProfiler::read.gmt("/projects/imb-pkbphil/sp/annotations/molsigdb/msigdb.v2023.1.Hs.symbols.gmt")
head(molsig); nrow(molsig)
##Pick gene sets to look in bcos all is a lot
prefixes = c("HALLMARK", "KEGG","REACTOME", "WP", "GOBP", "GOCC","GOMF")
colnames(molsig) = c("term","gene")
some.molsig = molsig[gsub("_.*","", molsig$term) %in% prefixes,]
some.molsig$term = factor(some.molsig$term)
table(gsub("_.*","", some.molsig$term))

shorten = function(ont) {
  abbreviate(gsub("_"," ", tolower(ont)),minlength=40, dot=T, named = F)
}
```
## Cluster GO

```{r}
clgo = compareCluster(gene~cluster, data=filter(cluster.markers,p_val_adj < 0.01), 
                      fun="enricher", TERM2GENE = some.molsig, universe = all.genes)
head(clgo)[,c(2,4:9)]
nrow(filter(clgo, p.adjust < 0.01))
summary(clgo@compareClusterResult$p.adjust)

dotplot(filter(clgo,p.adjust < 0.01), x="cluster", showCategory=2) 
dotplot(clgo, x="cluster", showCategory=2, includeAll=F) 
```

```{r pretty_unique}
dfgo = as.data.frame(clgo)
dfgo$short_desc =shorten(dfgo$Description)
go_to_plot = filter(dfgo, p.adjust < 0.01) %>% group_by(cluster) %>%
              slice_min(n = 2, order_by = p.adjust)
go_to_plot$short_desc = factor(go_to_plot$short_desc, levels=rev(unique(go_to_plot$short_desc)))

p = ggplot(go_to_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count)) + 
  geom_point()+  theme_bw(base_size=15) + 
  theme(axis.text.x=element_text(angle=30, hjust=1)) +scale_color_manual(values=clusters)
p
```
```{r pretty_overlapping}
include_all_plot = filter(dfgo, Description %in% go_to_plot$Description & p.adjust < 0.01)
include_all_plot$short_desc = factor(include_all_plot$short_desc, levels=levels(go_to_plot$short_desc))
a = ggplot(include_all_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count, alpha=Count)) + 
  geom_point()+  theme_bw(base_size=15) + 
  theme(axis.text.x=element_text(angle=30, hjust=1)) +scale_color_manual(values=clusters)
a
```

### Remove hallmark terms
```{r}
dfgo = as.data.frame(clgo)
dfgo$short_desc =shorten(dfgo$Description)
go_to_plot = filter(dfgo, !grepl("HALLMARK", Description) & p.adjust < 0.01) %>% group_by(cluster) %>%
              slice_min(n = 2, order_by = p.adjust)
go_to_plot$short_desc = factor(go_to_plot$short_desc, levels=rev(unique(go_to_plot$short_desc)))

p = ggplot(go_to_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count)) + 
  geom_point()+  theme_bw(base_size=15) + 
  theme(axis.text.x=element_text(angle=30, hjust=1)) +scale_color_manual(values=clusters)
p
```

```{r}
include_all_plot = filter(dfgo, Description %in% go_to_plot$Description & p.adjust < 0.01)
include_all_plot$short_desc = factor(include_all_plot$short_desc, levels=levels(go_to_plot$short_desc))
a = ggplot(include_all_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count)) + 
  geom_point()+  theme_bw(base_size=15) + 
  theme(axis.text.x=element_text(angle=30, hjust=1)) +scale_color_manual(values=clusters)
a
```

### GO on donor specific genes
```{r}
donorgo = compareCluster(gene~cluster, data=filter(donor.markers,p_val_adj < 0.01),
                         fun="enricher", TERM2GENE = some.molsig, universe = all.genes)
head(donorgo)[,c(2,4:9)]

p = dotplot(donorgo, showCategory=4, x="cluster") 
p + scale_y_discrete(labels=shorten(levels(p$data$Description)))
p = dotplot(donorgo, showCategory=4, x="cluster", includeAll=F) 
p + scale_y_discrete(labels=shorten(levels(p$data$Description)))
```

```{r}
dfgo = as.data.frame(donorgo)
dfgo$short_desc =shorten(dfgo$Description)
go_to_plot = filter(dfgo) %>% group_by(cluster) %>%
              slice_min(n = 4, order_by = p.adjust)
go_to_plot$short_desc = factor(go_to_plot$short_desc, levels=unique(rev(go_to_plot$short_desc)))

p = ggplot(go_to_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count)) + 
  geom_point()+  theme_bw(base_size=15) + 
  theme(axis.text.x=element_text(angle=30, hjust=1)) + scale_color_manual(values=pal)
p
```


```{r}
include_all_plot = filter(dfgo, Description %in% go_to_plot$Description & p.adjust < 0.01)
include_all_plot$short_desc = factor(include_all_plot$short_desc, levels=levels(go_to_plot$short_desc))
a = ggplot(include_all_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count, alpha=Count)) + 
  geom_point()+  theme_bw(base_size=15) + 
  theme(axis.text.x=element_text(angle=30, hjust=1)) + scale_color_manual(values=pal)
a
```

### Save 

```{r save} 
  write.table(clgo, here(odir, "ORA_marker_genes.txt"),
            sep="\t", row.names = F)
  write.table(donorgo, here(odir, "ORA_donor_marker_genes.txt"),
            sep="\t", row.names = F)
```
