---
title: "progenitors_rpca_cluster_stability"
author: "Sarah Hazell Pickering"
date: "2024-08-16"
output: html_document
---

Exploring cluster stability with clustree on resolutions 0.1 -> 1.2 and sch posthoc heirarchical clustering and statistcial testing

```{r libs, message=FALSE, warning=FALSE}
library(BPCells)
library(Seurat)
library(clusterProfiler)
library(clustree)
library(dplyr)
library(ggplot2)
library(ggsci)
library(here)
library(tidyr)
library(scSHC)
```

```{r params}
module = "progenitors"
dataname = "integration_trial"
load_data = T #Loading initial seurat analysis
subset_data = F

rmd_filename = "progenitors_rpca_clustree"
i_am(file.path("analysis", module, paste0(rmd_filename,".Rmd")))
odir = here("output", module, dataname)
```


```{r setup}
set.seed(8)
fig_dir = here("analysis", module, "figures", rmd_filename)
if (!dir.exists(fig_dir)) dir.create(fig_dir, recursive = TRUE)
knitr::opts_chunk$set(fig.path = paste0(fig_dir, "/"),
                      dev = c("png","pdf"))

if (!dir.exists(odir)) dir.create(odir, recursive = TRUE)
```


```{r themes}
theme_hp = theme_classic(base_size = 15) +
  theme(axis.line = element_line(linewidth = 0.25),
        axis.ticks = element_line(linewidth = 0.25),
        strip.background = element_blank())
theme_set(theme_hp)
pal = c("#DA1819", "#00AED1", "#434D51","#EBB400","#691A93","#3AAD00")
clusters = c("#DA1819","#691A93","#EBB400" , "#434D51","#00AED1","#3AAD00","#FF7F00","#AC8AD0", tvthemes::gravityFalls_pal()(12))
spectral = rev(RColorBrewer::brewer.pal(n = 11, name = 'Spectral'))
```

## load data

```{r}
if (subset_data){
  filt = readRDS(here(odir, "10%_complete_analysis.rds"))
} else{
  filt = readRDS(here(odir, "complete_analysis.rds"))
}
filt
table(filt$rpca_clusters)
```

```{r}
filt[["mnn.reconstructed"]] =NULL
filt = JoinLayers(filt)
Idents(filt) = "rpca_clusters"
filt
head(filt@meta.data) 
table(filt$rpca_clusters)

red_to_rm = grep("harmony|fastmnn", names(filt@reductions), value = T)
for (red in red_to_rm){
  print(paste0("red removed ", red))
  filt[[red]] = NULL
}
#set default reductions
filt[["umap"]] = filt[["umap.rpca"]]
filt[["tsne"]] = filt[["rpca.tsne"]]
filt
```

## Independent shc clustering

```{r}
counts = as.matrix(filt[["RNA"]]$counts)
denovo = scSHC(counts, batch=filt$subject, parallel=F)
table(denovo[[1]], filt$seurat_clusters)
```


```{r}
denovo[[2]]
```

```{r}
filt$denovo_shc = denovo[[1]]
DimPlot(filt, group.by=c("seurat_clusters","denovo_shc"), cols=clusters)
```


## save and or load

```{r eval=F}
saveRDS(filt, here(odir,"denovo_shc_clusters.rds"))
#filt = readRDS(here(odir,"multiple_resolutions.rds"))
```
