---
title: "marker_gene_ontologies"
author: "Sarah Hazell Pickering"
date: "2024-08-07"
output: html_document
---


```{r libs, message=FALSE, warning=FALSE}
library(ComplexHeatmap)
library(Seurat)
library(clusterProfiler, quietly = T)
library(dplyr)
library(enrichplot)
library(ggplot2)
library(here)
```

```{r params}
module = "progenitors"
dataname = "initial"
load_data = T
subset_data = F

rmd_filename = "progenitors_initial_markers_and_GO"
i_am(file.path("analysis", module, paste0(rmd_filename,".Rmd")))
odir = here("output", module, dataname)

```


```{r setup}
set.seed(8)
fig_dir = here("analysis", module, "figures", rmd_filename)
if (!dir.exists(fig_dir)) dir.create(fig_dir, recursive = TRUE)
knitr::opts_chunk$set(fig.path = paste0(fig_dir, "/"),
                      dev = c("png","pdf"))

if (!dir.exists(odir)) dir.create(odir, recursive = TRUE)
```


```{r themes}
theme_hp = theme_classic(base_size = 15) +
  theme(axis.line = element_line(linewidth = 0.25),
        axis.ticks = element_line(linewidth = 0.25),
        strip.background = element_blank())
theme_set(theme_hp)
pal = c('#0A7EA8','#EF5780','#0A8550','#1C31D3','#EE9614','#670F39')
names(pal) = paste0("S", 1:6)
clusters = c("#FED439FF", "#709AE1FF", "#8A9197FF", "#D2AF81FF",
             "#FD7446FF", "#D5E4A2FF", "#197EC0FF", "#46732EFF", "#71D0F5FF")
names(clusters) = 0:(length(clusters)-1)
spectral = rev(RColorBrewer::brewer.pal(n = 11, name = 'Spectral'))
```

## Load marker lists
```{r}
cluster.markers = read.delim(here(odir, "marker_genes.txt"))
cluster.markers = filter(cluster.markers, p_val_adj < 0.01)
all.genes = read.delim(here("data", "all.genes.txt"))[,1]
head(all.genes); length(all.genes)
donor.markers = read.delim(here(odir, "donor_marker_genes.txt"))
donor.markers = filter(donor.markers, p_val_adj < 0.01)
```

## load seurat object
```{r}
if (subset_data){
  filt = readRDS(here(odir, "10%_complete_analysis.rds"))
  Idents(filt) = "seurat_clusters"
} else{
  filt = readRDS(here(odir, "complete_analysis.rds"))
}
DimPlot(filt, cols=clusters)
```


## UMAP plots

```{r RidgePlot}
RidgePlot(filt,features = c("ACTA2","TAGLN"), slot="scale.data", cols=clusters)
VlnPlot(filt,features = c("MKI67","CDC20"))
VlnPlot(filt,features = c("CD36","TINAGL1"))
```

```{r u7u8markers, dev=c("png","pdf")}
FeaturePlot(filt, features = c("MKI67","CDC20","CD36","TINAGL1"), pt.size = 0.001) & 
  scale_colour_gradientn(colours = spectral)

for (gene in c("MKI67","CDC20","CD36","TINAGL1")){
  p =FeaturePlot(filt, gene, pt.size = 0.2) & 
  scale_colour_gradientn(colours = spectral)
  print(p)
}

```


## GO setup
```{r go_replace}
phrases= read.delim(here("data/gene_sets/abbreviations.txt"))
recap= read.delim(here("data/gene_sets/capitalisations.txt"))
```

```{r abrev_go}
drama_shorten = function(ont) {
  for (x in 1:nrow(phrases)){
    ont = gsub( phrases$phrase[x],phrases$abbreviation[x], ont, ignore.case = T)
  }
  a = abbreviate(gsub("_"," ", gsub("^[[:alpha:]]*_","",tolower(ont))),minlength=41, dot=T, named = F)
  a = stringr::str_to_sentence(a)
  for (i in 1:nrow(recap))
    a = gsub(sprintf("\\b%s\\b", recap$lowercase[i]),recap$capital[i],a, ignore.case = T)
  return(a)
}
```

```{r load_gene_sets}
molsig <- clusterProfiler::read.gmt(here("data/gene_sets/msigdb.v2024.1.Hs.symbols.gmt"))
head(molsig); nrow(molsig)

prefixes = c("HALLMARK", "KEGG","REACTOME", "WP", "GOBP", "GOCC","GOMF")
colnames(molsig) = c("term","gene")
some.molsig = molsig[gsub("_.*","", molsig$term) %in% prefixes,]
some.molsig$term = factor(some.molsig$term)
table(gsub("_.*","", some.molsig$term))
rm(molsig)
```
## Cluster GO

```{r}
clgo = compareCluster(gene~cluster, data=filter(cluster.markers,p_val_adj < 0.01), 
                      fun="enricher", TERM2GENE = some.molsig, universe = all.genes)
head(clgo)[,c(2,4:9)]
nrow(filter(clgo, p.adjust < 0.01))
summary(clgo@compareClusterResult$p.adjust)

dotplot(filter(clgo,p.adjust < 0.01), x="cluster", showCategory=2) 
dotplot(clgo, x="cluster", showCategory=2, includeAll=F) 
dotplot(clgo, x="cluster", showCategory=3, includeAll=F) 
```

```{r cluster_go_unique, dev=c("png","pdf")}
dfgo = as.data.frame(clgo)
dfgo$short_desc =drama_shorten(dfgo$Description)
go_to_plot = filter(dfgo, p.adjust < 0.01) %>% group_by(cluster) %>%
              slice_min(n = 2, order_by = p.adjust)
go_to_plot$short_desc = factor(go_to_plot$short_desc, levels=rev(unique(go_to_plot$short_desc)))

p = ggplot(go_to_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count)) + 
  geom_point() +scale_color_manual(values=clusters)
p
```
`

```{r cluster_go_overlapping_nohallmark, dev=c("png","pdf")}
include_all_plot = filter(dfgo, Description %in% go_to_plot$Description & p.adjust < 0.01)
include_all_plot$short_desc = factor(include_all_plot$short_desc, levels=levels(go_to_plot$short_desc))
a = ggplot(include_all_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count)) + 
  geom_point() +scale_color_manual(values=clusters)
a
```

## Cluster GO heatmaps
```{r}
top2_terms = go_to_plot[["ID"]]
top2_genelist = list()
for (n in unique(top2_terms)){
  top2_genelist[[n]] = some.molsig$gene[some.molsig$term == n]
}
str(top2_genelist)
```


```{r}
#set cluster levels
filt$seurat_clusters = factor(filt$seurat_clusters, levels=c(0,1,4,3,5,2,6,7,8))
```


```{r}
filt = AddModuleScore(filt, features = top2_genelist, name="top2GO")
colnames(filt@meta.data)[grep("top2GO",colnames(filt@meta.data))] = names(top2_genelist)
```



```{r}
sbs = subset(filt, downsample=100)
go_matrix= sbs@meta.data[names(top2_genelist)]
cell_ids = sbs@meta.data[c("subject","seurat_clusters")]
go_matrix = t(scale(data.matrix(go_matrix)))
go_matrix[1:3,1:3]
```

```{r}
ha = HeatmapAnnotation(cluster = cell_ids$seurat_clusters, col = list(cluster=clusters), show_legend = F,
                       show_annotation_name = F)
h =Heatmap(go_matrix, show_column_names = F, column_split = cell_ids$seurat_clusters, 
        show_heatmap_legend = F, top_annotation = ha, row_names_max_width = unit(9,"cm"))
h

h =Heatmap(go_matrix, show_column_names = F, column_split = cell_ids$seurat_clusters, 
        show_heatmap_legend = F, top_annotation = ha, row_names_max_width = unit(9,"cm"), 
        show_column_dend = F, cluster_column_slices = F)
h
```


## GO on donor specific genes
```{r}
donorgo = compareCluster(gene~cluster, data=filter(donor.markers,p_val_adj < 0.01),
                         fun="enricher", TERM2GENE = some.molsig, universe = all.genes)
head(donorgo)[,c(2,4:9)]

p = dotplot(donorgo, showCategory=3, x="cluster") 
p + scale_y_discrete(labels=drama_shorten(levels(p$data$Description)))
p = dotplot(donorgo, showCategory=3, x="cluster", includeAll=F) 
p + scale_y_discrete(labels=drama_shorten(levels(p$data$Description)))
```

```{r donor_go_unique, dev=c("png","pdf")}
dfgo = as.data.frame(donorgo)
dfgo$short_desc =drama_shorten(dfgo$Description)
dfgo$cluster = factor(dfgo$cluster, levels=paste0("S",c(1,5,6,2,4,3)))
go_to_plot = filter(dfgo, p.adjust < 0.01) %>% group_by(cluster) %>%
              slice_min(n = 3, order_by = tibble(p.adjust, pvalue))
go_to_plot$short_desc = factor(go_to_plot$short_desc, levels=rev(unique(go_to_plot$short_desc)))

p = ggplot(go_to_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count)) + 
  geom_point() + scale_color_manual(values=pal)
p
```


```{r donor_go_overlapping, dev=c("png","pdf")}
include_all_plot = filter(dfgo, Description %in% go_to_plot$Description & p.adjust < 0.01)
include_all_plot$short_desc = factor(include_all_plot$short_desc, levels=levels(go_to_plot$short_desc))
a = ggplot(include_all_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count, alpha=Count)) + 
  geom_point() + scale_color_manual(values=pal)
a
```


### reorder dotplot
Moving common terms tothe bottom of the plot to make it easier to read.  
```{r donor_go_sorted, dev=c("png","pdf")}
include_all_plot$short_desc = factor(include_all_plot$short_desc, 
                                     levels=unique(c("gocccollagencontainingextracellularmatrx.",
                                                     "gobp connective tissue development",
                                                   "gocc cell substrate junction" ,
                                                   "gobp cartilage development",
                                                   levels(go_to_plot$short_desc))))
a = ggplot(include_all_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count, alpha=Count)) + 
  geom_point()+ scale_color_manual(values=pal[paste0("S",c(1,5,6,2,4,3))])
a
```



### Donor-specific GO heatmap
```{r}
top2_terms = go_to_plot[["ID"]]
top2_genelist = list()
for (n in unique(top2_terms)){
  top2_genelist[[n]] = some.molsig$gene[some.molsig$term == n]
}
str(top2_genelist)
```


```{r}
filt = AddModuleScore(filt, features = top2_genelist, name="top2GO")
colnames(filt@meta.data)[grep("top2GO",colnames(filt@meta.data))] = names(top2_genelist)
```


```{r}
Idents(filt) = "subject"
sbs = subset(filt, downsample=100)
go_matrix= sbs@meta.data[names(top2_genelist)]
cell_ids = sbs@meta.data[c("subject","seurat_clusters")]
cell_ids$subject = factor(cell_ids$subject, levels=names(pal))
go_matrix = t(scale(data.matrix(go_matrix)))
go_matrix[1:3,1:3]
```


```{r}
ha = HeatmapAnnotation(subject = cell_ids$subject, col = list(subject=pal), show_legend = F,
                       show_annotation_name = F)
h =Heatmap(go_matrix, show_column_names = F, column_split = cell_ids$subject, 
        show_heatmap_legend = F, top_annotation = ha, row_names_max_width = unit(9,"cm"),
        cluster_column_slices = T, show_column_dend = T)
h
```

### Save 

```{r save} 
  write.table(clgo, here(odir, "ORA_marker_genes.txt"),
            sep="\t", row.names = F)
  write.table(donorgo, here(odir, "ORA_donor_marker_genes.txt"),
            sep="\t", row.names = F)
```
