---
title: "progenitors_rpca_cluster_trees"
author: "Sarah Hazell Pickering"
date: "2024-08-16"
output: html_document
---

Testing clusters found at 0.3 and 0.5 resolution -> and making a tree for larger cluster differences.  

```{r params}
module="progenitors"
dataname = "integration_trial"
library(here);#i_am(file.path("analysis",paste(module,sep="_","rpca_clustree.Rmd")))
i_am(file.path("analysis",module,paste(module,sep="_","rpca_clustree.Rmd")))
odir = here("output", module, dataname) 

load_data = T #Loading initial seurat analysis
subset_data =  F

if (!dir.exists(odir)){dir.create(odir, recursive = T)}
```


```{r libs, warning=F, message=F, echo=T}
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggsci)

library(Seurat)
library(BPCells)
library(clustree)

pal = c("#DA1819", "#00AED1", "#434D51","#EBB400","#691A93","#3AAD00")
clusters = ggsci::pal_simpsons()(13)[c(1:7,9:13)]
spectral =  rev(RColorBrewer::brewer.pal(n = 11, name = "Spectral"))
```


```{r}
if (subset_data){
  filt = readRDS(here(odir, "10%_complete_analysis.rds"))
} else{
  filt = readRDS(here(odir, "complete_analysis.rds"))
}
filt
table(filt$rpca_clusters)
```

```{r}
filt[["mnn.reconstructed"]] =NULL
filt = JoinLayers(filt)
Idents(filt) = "rpca_clusters"
filt
head(filt@meta.data) 
table(filt$rpca_clusters)

red_to_rm = grep("harmony|fastmnn", names(filt@reductions), value = T)
for (red in red_to_rm){
  print(paste0("red removed ", red))
  filt[[red]] = NULL
}
#set default reductions
filt[["umap"]] = filt[["umap.rpca"]]
filt[["tsne"]] = filt[["rpca.tsne"]]
filt
```



```{r}
res_to_test = c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8)
filt = FindNeighbors(filt, dims=1:20, reduction = "integrated.rpca")
for (res in res_to_test){
  filt = FindClusters(filt, resolution = res, cluster.name = paste0("res",res,"_clusters"))
}

head(filt@meta.data)
table(filt$res0.5_clusters)
table(filt$rpca_clusters)
```


```{r}
clustree(filt, prefix="res", suffix ="_clusters")
clustree(filt, prefix="res", suffix ="_clusters", node_colour="sc3_stability")
```

```{r}
DimPlot(filt, group.by = "res0.1_clusters")
DimPlot(filt, group.by = "res0.5_clusters") + scale_color_manual(values=clusters)
DimPlot(filt, group.by = "res0.4_clusters") + scale_color_manual(values=clusters) #Keep res0.5 clu7 separate
DimPlot(filt, group.by = "res0.3_clusters") + scale_color_manual(values=clusters) #Or merge clu7
DimPlot(filt, group.by = "res0.2_clusters") + scale_color_manual(values=clusters) #merge cell cycle and subject2
```


## composition with 0.5 resolution

```{r}
composition = group_by(filt@meta.data, subject,res0.5_clusters) %>% count()
composition = composition[order(composition$n, decreasing = T),]
colnames(composition) = c("donor_id","seurat_clusters","n_cells")
#Calculate proportions
composition = group_by(composition, donor_id) %>% mutate(cells_per_donor = n_cells/sum(n_cells))
composition = group_by(composition, seurat_clusters) %>% mutate(cells_per_cluster = n_cells/sum(n_cells))
head(composition)
```


```{r }
ggplot(composition) + geom_bar(stat="identity",aes(y=donor_id, x=n_cells, fill=seurat_clusters)) + 
  scale_y_discrete(limits=rev)+ scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15) + scale_fill_manual(values=clusters)
ggplot(composition) + geom_bar(stat="identity",aes(y=donor_id, x=n_cells, fill=seurat_clusters), position = "fill") +
  scale_y_discrete(limits=rev)+ scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15)  + scale_fill_manual(values=clusters)
```

```{r }
ggplot(composition) + geom_bar(stat="identity",aes(fill=donor_id, x=n_cells, y=seurat_clusters)) +
    scale_y_discrete(limits=rev)+ scale_fill_manual(values=pal)  + scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15)
ggplot(composition) + geom_bar(stat="identity",aes(fill=donor_id, x=n_cells, y=seurat_clusters), position = "fill") +
  scale_y_discrete(limits=rev)+ scale_fill_manual(values=pal)  + scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15)
```

```{r}
ggplot(filter(composition, seurat_clusters %in% c(0,1,2,3))) + 
         geom_bar(stat="identity",aes(y=donor_id, x=n_cells, fill=seurat_clusters)) + 
  scale_y_discrete(limits=rev)+ scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15) + scale_fill_manual(values=clusters)
ggplot(filter(composition, seurat_clusters %in% c(0,1,2,3))) + geom_bar(stat="identity",aes(y=donor_id, x=n_cells, fill=seurat_clusters), position = "fill") +
  scale_y_discrete(limits=rev)+ scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15)  + scale_fill_manual(values=clusters)
```

## Markers on 0.5 resolution

```{r}
Idents(filt) = "res0.5_clusters"
cluster.markers = FindAllMarkers(filt, min.pct=0.25, logfc.threshold=0.5, 
                              densify=T, only.pos=T)
head(cluster.markers); dim(cluster.markers)
table(filter(cluster.markers,p_val_adj < 0.01) %>% pull(cluster))

top.markers = as.data.frame(cluster.markers) %>%
    group_by(cluster) %>% filter(p_val_adj < 0.01) %>%
    slice_max(n=2, order_by = avg_log2FC*pct.1)
top.markers


cluster.markers$cluster = factor(cluster.markers$cluster, levels=0:max(as.integer(cluster.markers$cluster)))
uniq.cluster.markers = cluster.markers[!cluster.markers$gene %in% names(which(table(cluster.markers$gene) > 1)),]
head(cluster.markers)
```

```{r}
table(cluster.markers$cluster)
table(uniq.cluster.markers$cluster)
```


Cluster unique-ness as measured by marker gene overlaps
```{r}
clu_uniq = as.data.frame(cbind(table(cluster.markers$cluster),table(uniq.cluster.markers$cluster)))
colnames(clu_uniq)= c("all","uniq")
clu_uniq = mutate(clu_uniq, prop_lost = (clu_uniq$all - clu_uniq$uniq )/clu_uniq$all, n_lost = clu_uniq$all - clu_uniq$uniq)
clu_uniq
```



## GO setup
```{r}
molsig <- clusterProfiler::read.gmt("/projects/imb-pkbphil/sp/annotations/molsigdb/msigdb.v2023.1.Hs.symbols.gmt")
head(molsig); nrow(molsig)
##Pick gene sets to look in bcos all is a lot
prefixes = c("HALLMARK", "KEGG","REACTOME", "WP", "GOBP", "GOCC","GOMF")
colnames(molsig) = c("term","gene")
some.molsig = molsig[gsub("_.*","", molsig$term) %in% prefixes,]
some.molsig$term = factor(some.molsig$term)
table(gsub("_.*","", some.molsig$term))

shorten = function(ont) {
  abbreviate(gsub("_"," ", tolower(ont)),minlength=40, dot=T, named = F)
}
```
## Cluster GO

```{r}
library(clusterProfiler)
all.genes=rownames(filt)
clgo = compareCluster(gene~cluster, data=filter(uniq.cluster.markers,p_val_adj < 0.01), 
                      fun="enricher", TERM2GENE = some.molsig, universe = all.genes)

clgo = mutate(clgo, cluster = factor(cluster, levels=c(0,1:max(as.integer(cluster)))))
table(clgo@compareClusterResult$cluster)
head(clgo)[,c(2,4:9)]
nrow(filter(clgo, p.adjust < 0.01))
summary(clgo@compareClusterResult$p.adjust)

dotplot(filter(clgo,p.adjust < 0.01), x="cluster", showCategory=2) 
dotplot(clgo, x="cluster", showCategory=2, includeAll=F) 
```
lumenal side of ER: HLA-B/HLA-A/PKD2/HLA-DRB1/HLA-E/HLA-F/HLA-DPB1 Not so sure about that.  

```{r cluster_go_, dev=c("png","pdf")}
dfgo = as.data.frame(clgo)
dfgo$short_desc =shorten(dfgo$Description)
go_to_plot = filter(dfgo, p.adjust < 0.01) %>% group_by(cluster) %>%
              slice_min(n = 2, order_by = p.adjust)
go_to_plot$short_desc = factor(go_to_plot$short_desc, levels=rev(unique(go_to_plot$short_desc)))

p = ggplot(go_to_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count)) + 
  geom_point()+  theme_bw(base_size=15) + 
  theme(axis.text.x=element_text(angle=30, hjust=1)) +scale_color_manual(values=clusters)
p
```


```{r}
go_to_plot[c(2,3,5,6,8,11,10)]
```

## Markers on 0.3 resolution

```{r}
Idents(filt) = "res0.3_clusters"
res0.3_markers = FindAllMarkers(filt,min.pct=0.25,only.pos=T, logfc.threshold=0.5,densify=T)
res0.3_markers = filter(res0.3_markers, p_val_adj < 0.01)
```

```{r}
nrow(res0.3_markers)
summary(res0.3_markers$p_val_adj < 0.01)
```

```{r}
top.markers = as.data.frame(res0.3_markers) %>%
    group_by(cluster) %>% filter(p_val_adj < 0.01) %>%
    slice_max(n=2, order_by = avg_log2FC*pct.1)
top.markers
```


```{r marker_dotplot, dev=c('png','pdf')}
DotPlot(filt, features=rev(unique(top.markers$gene))) & 
  scale_colour_gradientn(colours = spectral) & coord_flip()

top.markers$gene = factor(top.markers$gene, levels=rev(unique(top.markers$gene)))
overlap.to.plot = filter(res0.3_markers, gene %in% top.markers$gene)
overlap.to.plot$gene = factor(overlap.to.plot$gene, levels=levels(top.markers$gene))

ggplot(overlap.to.plot, aes(y=gene, size=abs(avg_log2FC), color=cluster,
                    x=cluster)) + 
  geom_point() + 
  theme_bw(base_size=15)  + 
  theme(axis.text.x=element_text(angle=30, hjust=1))  + 
  scale_color_manual(values=clusters)
```


```{r}
table(res0.3_markers$cluster)
uniq.0.3.markers= res0.3_markers[!res0.3_markers$gene %in% names(which(table(res0.3_markers$gene) > 1)),]
table(uniq.0.3.markers$cluster)
```
```{r}
clu_uniq = as.data.frame(cbind(table(res0.3_markers$cluster),table(uniq.0.3.markers$cluster)))
colnames(clu_uniq)= c("all","uniq")
clu_uniq = mutate(clu_uniq, prop_lost = (clu_uniq$all - clu_uniq$uniq )/clu_uniq$all, n_lost = clu_uniq$all - clu_uniq$uniq)
clu_uniq
```


```{r}
clgo = compareCluster(gene~cluster, data=filter(res0.3_markers,p_val_adj < 0.01), 
                      fun="enricher", TERM2GENE = some.molsig, universe = all.genes)

clgo = mutate(clgo, cluster = factor(cluster, levels=c(0,1:max(as.integer(cluster)))))
table(clgo@compareClusterResult$cluster)
head(clgo)[,c(2,4:9)]
nrow(filter(clgo, p.adjust < 0.01))
summary(clgo@compareClusterResult$p.adjust)

dotplot(filter(clgo,p.adjust < 0.01), x="cluster", showCategory=2) 
dotplot(clgo, x="cluster", showCategory=2, includeAll=F) 
```


```{r}
clgo = compareCluster(gene~cluster, data=filter(uniq.0.3.markers,p_val_adj < 0.01), 
                      fun="enricher", TERM2GENE = some.molsig, universe = all.genes)

clgo = mutate(clgo, cluster = factor(cluster, levels=c(0,1:max(as.integer(cluster)))))
table(clgo@compareClusterResult$cluster)
head(clgo)[,c(2,4:9)]
nrow(filter(clgo, p.adjust < 0.01))
summary(clgo@compareClusterResult$p.adjust)

dotplot(filter(clgo,p.adjust < 0.01), x="cluster", showCategory=2) 
dotplot(clgo, x="cluster", showCategory=2, includeAll=F) 
```

```{r cluster_go, dev=c("png","pdf")}
dfgo = as.data.frame(clgo)
dfgo$short_desc =shorten(dfgo$Description)
go_to_plot = filter(dfgo, p.adjust < 0.01) %>% group_by(cluster) %>%
              slice_min(n = 2, order_by = p.adjust)
go_to_plot$short_desc = factor(go_to_plot$short_desc, levels=rev(unique(go_to_plot$short_desc)))

p = ggplot(go_to_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count)) + 
  geom_point()+  theme_bw(base_size=15) + 
  theme(axis.text.x=element_text(angle=30, hjust=1)) +scale_color_manual(values=clusters)
p
```

```{r}
table(dfgo$cluster)
```

```{r overlapping, dev=c("png","pdf")}
include_all_plot = filter(dfgo, Description %in% go_to_plot$Description & p.adjust < 0.01)
include_all_plot$short_desc = factor(include_all_plot$short_desc, levels=levels(go_to_plot$short_desc))
a = ggplot(include_all_plot, aes(x=cluster, y=short_desc, colour=cluster, size=Count)) + 
  geom_point()+  theme_bw(base_size=15) + 
  theme(axis.text.x=element_text(angle=30, hjust=1)) +scale_color_manual(values=clusters)
a
```

## Cluster composition
```{r}
umap_name="umap.rpca"
clu_name = "res0.3_clusters"
DimPlot(filt, split.by="subject", reduction = umap_name, ncol=3, group.by="subject", combine=F, cols = pal)

DimPlot(filt, split.by="subject", reduction = umap_name, ncol=3, group.by=clu_name, combine=F, cols = clusters)
```

```{r}
composition = group_by(filt@meta.data, subject,res0.3_clusters) %>% count()
composition = composition[order(composition$n, decreasing = T),]
colnames(composition) = c("donor_id","seurat_clusters","n_cells")
#Calculate proportions
composition = group_by(composition, donor_id) %>% mutate(cells_per_donor = n_cells/sum(n_cells))
composition = group_by(composition, seurat_clusters) %>% mutate(cells_per_cluster = n_cells/sum(n_cells))
head(composition)
```


```{r }
ggplot(composition) + geom_bar(stat="identity",aes(y=donor_id, x=n_cells, fill=seurat_clusters)) + 
  scale_y_discrete(limits=rev)+ scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15) + scale_fill_manual(values=clusters)
ggplot(composition) + geom_bar(stat="identity",aes(y=donor_id, x=n_cells, fill=seurat_clusters), position = "fill") +
  scale_y_discrete(limits=rev)+ scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15)  + scale_fill_manual(values=clusters)
```

```{r }
ggplot(composition) + geom_bar(stat="identity",aes(fill=donor_id, x=n_cells, y=seurat_clusters)) +
    scale_y_discrete(limits=rev)+ scale_fill_manual(values=pal)  + scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15)
ggplot(composition) + geom_bar(stat="identity",aes(fill=donor_id, x=n_cells, y=seurat_clusters), position = "fill") +
  scale_y_discrete(limits=rev)+ scale_fill_manual(values=pal)  + scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15)
```


```{r}
ggplot(filter(composition, seurat_clusters %in% c(0,1,2,3))) + 
         geom_bar(stat="identity",aes(y=donor_id, x=n_cells, fill=seurat_clusters)) + 
  scale_y_discrete(limits=rev)+ scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15) + scale_fill_manual(values=clusters)
ggplot(filter(composition, seurat_clusters %in% c(0,1,2,3))) + geom_bar(stat="identity",aes(y=donor_id, x=n_cells, fill=seurat_clusters), position = "fill") +
  scale_y_discrete(limits=rev)+ scale_x_continuous(expand = c(0.01, 0))+ 
  theme_classic(base_size=15)  + scale_fill_manual(values=clusters)
```

