---
title: "progenitors_rpca_umi_regress_out"
author: "Sarah Hazell Pickering"
date: "2024-08-19"
output: html_document
---


```{r params}
module="progenitors"
dataname = "rpca"
library(here);i_am(file.path("analysis",paste(module,sep="_",dataname, "clusters_and_markers.Rmd")))
odir = here("output", module, dataname) 

load_data = T #Loading initial seurat analysis
subset_data =  F

if (!dir.exists(odir)){dir.create(odir, recursive = T)}
```


```{r libs, warning=F, message=F, echo=T}
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggsci)

library(Seurat)
library(BPCells)
library(clustree)

pal = c("#DA1819", "#00AED1", "#434D51","#EBB400","#691A93","#3AAD00")
clusters = ggsci::pal_simpsons()(13)[c(1:7,9:13)]
spectral =  rev(RColorBrewer::brewer.pal(n = 11, name = "Spectral"))
```


```{r}
if (subset_data){
  filt = readRDS(here(odir, "10%_complete_analysis.rds"))
} else{
  filt = readRDS(here(odir, "complete_analysis.rds"))
}
filt
```

Overwrite warning: Warning: Different features in new layer data than already exists for scale.data

```{r}
filt = ScaleData(filt, vars.to.regress = c("nCount_RNA"))
filt
```

```{r}
filt = FindVariableFeatures(filt)
filt = RunPCA(filt, nfeatures.print = 5)
```

```{r}
filt = RunUMAP(filt, dims = 1:20)
DimPlot(filt, group.by="rpca_clusters",cols=clusters)
FeaturePlot(filt, "nCount_RNA") & scale_color_gradientn(colours=spectral)
```


