---
title: "bulk_day15_GO"
author: "Sarah Hazell Pickering"
date: "2025-01-21"
output: html_document
---



```{r}
library(here); i_am("analysis/bulk/bulk_day15_mitopathways.Rmd")
knitr::opts_knit$set(dev=c("png","pdf"))
odir = here("output/bulk")
figdir = here(odir,"plots")
if (!dir.exists(figdir)){dir.create(figdir, recursive = T)}
```

```{r message=FALSE, warning=FALSE, echo=TRUE}
library(tidyr)
library(dplyr)
library(clusterProfiler)
library(enrichplot)
library(ggplot2)
theme_set(theme_classic(base_size=15) + 
  theme(axis.title.y=element_blank(),axis.text.y = element_text(size=12),
        axis.line = element_line(linewidth = 0.25),
        axis.ticks = element_line(linewidth=0.25)))

library(stringr)
library(viridis)
pal = c("#DA1819", "#00AED1", "#434D51","#EBB400","#691A93","#3AAD00")
```


```{r}
go <- clusterProfiler::read.gmt("/projects/imb-pkbphil/sp/annotations/molsigdb/c5.all.v2024.1.Hs.symbols.gmt")
go= go[gsub("_.*","", go$term) %in% "GOCC",]

h <- clusterProfiler::read.gmt("/projects/imb-pkbphil/sp/annotations/molsigdb/h.all.v2024.1.Hs.symbols.gmt")
molsig = rbind(go, h)
head(molsig); nrow(molsig)
molsig$term = factor(molsig$term)
table(gsub("_.*","", molsig$term))
rm(go,h)
```

```{r}
sig = read.delim(file="https://raw.githubusercontent.com/sarahhp/splicing_thermogenesis/main/03limma/any_and_all_donor_DGE.tsv")
head(sig)
nrow(sig)
tail(sig)

summary(sig$all.donors.adj.P.Val < 0.01)
```

```{r}
make_gene_list = function(sig, donor){
  gl = sig[,paste0("logFC.",donor)]
  names(gl) = sig$gene_name
  gl = gl[order(gl, decreasing = T)]
  return (gl)
}


allgl = list()
for (donor in c("s1","s2","s3","s4","s5","s6")){
  print(donor)
  gl = make_gene_list(sig, donor)
  allgl[[donor]] = gl
}
str(allgl)
```

```{r}
allea = compareCluster(allgl, fun=GSEA, TERM2GENE=molsig, pvalueCutoff=1, minGSSize=3, eps=1e-40)
allea = arrange(allea, p.adjust, abs(NES))
head(allea)
summary(allea@compareClusterResult$p.adjust)
nrow(allea)
```

```{r}
write.table(as.data.frame(allea), here(odir, "gocc_hallmark_GSEA.tsv"),
            sep="\t", quote=F, row.names = F)
```


Alpha matters here for the includeAll plots

## Alpha 0.05
```{r}
filt = filter(allea, p.adjust < 0.01) 
```

NES = Normalised enrichment score

```{r go5}
dotplot(filt, showCategory=6, includeAll=T, color="NES") + scale_colour_viridis(option="mako", direction=-1)
dotplot(filt, showCategory=2, includeAll=T, color="NES") + scale_colour_viridis(option="mako", direction=-1)
```


```{r}
top2 = filter(as_tibble(allea), NES > 0 & p.adjust < 1e-10 & ID != "GOCC_MITOCHONDRIAL_PROTEIN_CONTAINING_COMPLEX" ) %>% 
  slice_min(tibble(p.adjust,desc(NES)), n=2, by=Cluster)
w2 = filter(as_tibble(allea), NES < 0 & p.adjust < 1e-10) %>% slice_min(tibble(p.adjust,NES), n=2, by=Cluster)

top2 = rbind(top2, w2) %>% mutate(condition=if_else(NES>0,"beige","white"))
top2[,c(1:2,4:11)]
top2$ID = factor(top2$ID, levels = unique(c(w2$ID, top2$ID)))
```


```{r}
ggplot(top2,aes(x=Cluster, y=ID, color=condition, size=-log10(p.adjust))) + geom_point() +
  scale_color_manual(values = c("orange","cyan3")) 
```

```{r top2pfilt}
include_all_plot = filter(as_tibble(allea), Description %in% top2$Description& p.adjust < 0.05) %>%
  mutate(condition=if_else(NES>0,"beige","white"))
include_all_plot$ID = factor(include_all_plot$ID, levels=levels(top2$ID))

shorten = function(ont){
  str_wrap(str_to_title(gsub("_|GOCC"," ",ont)), width=30)
}

ggplot(include_all_plot,aes(x=Cluster, y=ID, color=condition, alpha=abs(NES))) + geom_point(size=10) +
  scale_color_manual(values = c("#FF7F00","#1F78B4")) + xlab("Subject") + 
  scale_y_discrete(labels= function(ID) shorten(ID)) 
ggsave(here(figdir,"day15_GSEA_top2filt.pdf"), width = 7, height=4)

```

