---
title: "bulk_day15_UCP1_expr"
author: "Sarah Hazell Pickering"
date: "2025-01-21"
output: html_document
---

```{r libs, message=FALSE, warning=FALSE}
library(dplyr)
library(ggbeeswarm)
library(ggplot2)
library(ggprism)
library(here)
library(stringr)
library(tidyr)
library(viridis)
```

```{r params}
module = "bulk"
dataname = "day15"
load_data = T
subset_data = F

```


```{r setup}
set.seed(8)
rmd_filename = "bulk_day15_UCP1_expr"
i_am(file.path("analysis","bulk",paste0(rmd_filename,".Rmd")))
fig_dir = here("analysis", module, "figures", rmd_filename)
if (!dir.exists(fig_dir)) dir.create(fig_dir, recursive = TRUE)
knitr::opts_chunk$set(fig.path = paste0(fig_dir, "/"),
                      dev = c("png","pdf"))
```


```{r themes}
theme_hp = theme_classic(base_size = 15) +
  theme(axis.line = element_line(linewidth = 0.25),
        axis.ticks = element_line(linewidth = 0.25),
        strip.background = element_blank())
theme_set(theme_hp)
pal = c("#DA1819", "#00AED1", "#434D51", "#EBB400", "#691A93", "#3AAD00")
```


```{r}
load(file=url("https://raw.githubusercontent.com/sarahhp/splicing_thermogenesis/refs/heads/main/03limma/rpkm_rep_for_plotting.RData"))
long = mutate(long, subject=gsub("subject","S", donor))
head(long)
sig = read.delim(file="https://raw.githubusercontent.com/sarahhp/splicing_thermogenesis/main/03limma/any_and_all_donor_DGE.tsv")
sig[sig$gene_name == "UCP1",]
filter(sig, gene_name == "UCP1") %>% select(matches("adj.P.Val|logFC"))
```
^ p-values from limma DEG analysis < 1.36 x 10^-5

```{r}
across = read.delim(here("output/bulk/beige_DGE_between_subjects.tsv"))
across =  mutate(across, ave.adj.p =( adj.P.Val.s1 + adj.P.Val.s2 +adj.P.Val.s3 +adj.P.Val.s4 + adj.P.Val.s5 +adj.P.Val.s6)/6,
                 if_any = ((adj.P.Val.s1 < 0.01) + 
                         (adj.P.Val.s2 < 0.01) +
                         (adj.P.Val.s3 < 0.01) +
                         (adj.P.Val.s4 < 0.01) + 
                         (adj.P.Val.s5 < 0.01) +
                         (adj.P.Val.s6 < 0.01) > 0 ))
head(across[c(2,29,30)])
across = arrange(across, ave.adj.p)
head(across, n=20)


summary(sig$all.donors.adj.P.Val < 0.01)
summary(across$if_any)

summary((filter(sig, all.donors.adj.P.Val < 0.01) %>% pull(gene_name)) %in% 
          (filter(across, if_any) %>% pull(gene_name)))
```
^ between subject pvalues (beige vs average )



```{r}
assign_p_stars = function(pval){
  return(
  if_else(pval < 0.0001, "***",
          if_else(pval < 0.001, "**",
                if_else(pval < 0.01, "*", "n.s."))))
}

assign_p_snake = function(pval){
  return(
  if_else(pval < 0.0001, "§§§",
          if_else(pval < 0.001, "§§",
                if_else(pval < 0.01, "§", "n.s."))))
}

adjust_y_pos = function(to_plot, genes, adj_val = 0.25){
  y_pos = c()
  for (gene in genes){
    max_fpkm = filter(to_plot, gene_name == gene) %>% pull(fpkm) %>% max()
   y_pos = c(y_pos, max_fpkm +  max_fpkm * adj_val)
  }
  return(y_pos)
}

get_pvals = function(sig_df, genes, expr){
    p_tab = filter(sig_df, gene_name %in% genes) %>% select(matches("adj.P.Val|gene_name")) %>% 
        pivot_longer(matches("\\.s?"), names_to = "subject", values_to ="adj.P.Val",
                     names_transform = function(x){gsub("adj.P.Val.s","S", x)} ) 
  
    subject_p = filter(p_tab, subject != "all.donors.adj.P.Val") %>%
                       mutate(group1="white",group2="beige",.before="subject", condition="white", 
          adj.p.star = assign_p_stars(adj.P.Val), p.round = signif(round(adj.P.Val, 3),1)) %>% arrange (gene_name)
    
    to_plot = filter(expr, gene_name %in% genes)
    subject_p = mutate(subject_p, y.position = adjust_y_pos(to_plot, gene_name))
    return (subject_p)
}
```





```{r}
plot_genes = function(expr, sig_df, genes){
    to_plot = filter(expr, gene_name %in% genes)
    pvals = get_pvals(sig_df, genes, expr)
    pvals
    
    
    g = ggplot( to_plot, 
             aes(x=subject, y=fpkm, fill=condition)) +
        geom_bar(stat = "summary", fun=mean, position=position_dodge2(preserve="single"))  + 
        geom_beeswarm(dodge.width=0.9, cex=2, size=0.8) + 
        scale_fill_manual(values = c("#1F78B4","#FF7F00"), name="Condition", labels = c("White", "Beige"))   +
        facet_wrap(~gene_name, scales="free_y", axes="all_x", axis.labels="margins") +
        add_pvalue(pvals, x="subject",label="adj.p.star", label.size = 3) +
        scale_y_continuous(expand =expansion(mult=c(0,0.05))) + 
        labs(y="Gene expression (FPKM)",x="Subject") 
    print(g)
    ggsave(here(fig_dir, paste0(paste0(genes,collapse="."),"_RNA_expr.pdf")))
}


genes = c("UCP1","CIDEA","CITED1","PPARGC1A")
genes = c("UCP1","CIDEA","CITED1","PDK4")
plot_genes(long, sig, genes)

genes = c("FASN","ACLY","LPL","PDK4")
genes = c("FASN","PM20D1","CKMT1B","CD36")
plot_genes(long, sig, genes)

```

### Add between subject pval

```{r}
genes = c("UCP1","CIDEA","CITED1","PM20D1")
to_plot = filter(long, gene_name %in% genes)
pvals = get_pvals(sig, genes, long)
pvals

p_tab = filter(across, gene_name %in% genes) %>% select(matches("adj.P.Val|gene_name")) %>% 
        pivot_longer(matches("\\.s?"), names_to = "subject", values_to ="adj.P.Val",
                     names_transform = function(x){gsub("adj.P.Val.s","S", x)} ) 
  
subject_p =  mutate(p_tab, before="subject",group1=subject,condition="beige",
          adj.p.star = assign_p_snake(adj.P.Val), 
          p.round = signif(round(adj.P.Val, 3),1),
           y.position = adjust_y_pos(to_plot, gene_name, adj_val=0.1)) %>% arrange (gene_name)
    


g = ggplot( to_plot, 
         aes(x=subject, y=fpkm, fill=condition)) +
    geom_bar(stat = "summary", fun=mean, position=position_dodge2(preserve="single"))  + 
    geom_beeswarm(dodge.width=0.9, cex=2, size=0.8) + 
    scale_fill_manual(values = c("#1F78B4","#FF7F00"), name="Condition",labels = c("White", "Beige"))   +
    facet_wrap(~gene_name, scales="free_y", axes="all_x", axis.labels="margins") +
    add_pvalue(pvals, x="subject",label="adj.p.star", label.size = 4) +
    scale_y_continuous(expand =expansion(mult=c(0,0.05))) + 
    labs(y="Gene expression (FPKM)",x="Subject")  +
    add_pvalue(subject_p, x="subject",label="adj.p.star", label.size = 3, y.position = )

print(g)
ggsave(here(fig_dir, paste0(paste0(genes,collapse="."),"_RNA_expr_two_stats.pdf")))
```




```{r}
genes = c("UCP1","CIDEA","CITED1","ALPL")
  p_tab = filter(sig, gene_name %in% genes) %>% select(matches("adj.P.Val|gene_name")) %>% 
        pivot_longer(matches("\\.s?"), names_to = "subject", values_to ="adj.P.Val",
                     names_transform = function(x){gsub("adj.P.Val.s","S", x)} ) 
  print(p_tab)
  
  subject_p = filter(p_tab, subject != "all.donors.adj.P.Val") %>%
                       mutate(group1="white",group2="beige",.before="subject", condition="white", 
         adj.p.star = assign_p_stars(adj.P.Val), p.round = signif(round(adj.P.Val, 3),1)) %>% arrange (gene_name)
  
  to_plot = filter(long, gene_name %in% genes)
  subject_p = mutate(subject_p, y.position = adjust_y_pos(to_plot, gene_name))
  
  g = ggplot( to_plot, 
         aes(x=subject, y=fpkm, fill=condition)) +
    geom_bar(stat = "summary", fun=mean, position=position_dodge2(preserve="single"))  + 
    geom_beeswarm(dodge.width=0.9, cex=2, size=0.8) + 
    scale_fill_manual(values = c("#1F78B4","#FF7F00"), name="Condition", labels = c("Beige","White"))   +
    facet_wrap(~gene_name, scales="free_y", axes="all_x", axis.labels="margins") +
    add_pvalue(subject_p, x="subject",label="adj.p.star", label.size = 3) +
    scale_y_continuous(expand =expansion(mult=c(0,0.05))) + 
    labs(y="Gene expression (FPKM)",x="Subject") 
  print(g)
ggsave(here(fig_dir, paste0(paste0(genes,collapse="."),"_RNA_expr.pdf")))

```


```{r ucp1}
ggplot(filter(long, gene_name == "UCP1"), 
         aes(x=subject, y=fpkm, fill=condition)) +
    geom_bar(stat = "summary", fun=mean, position=position_dodge2(preserve="single"))  + 
    geom_beeswarm(dodge.width=0.9, cex=1.5) + 
    scale_fill_manual(values = c("#1F78B4","#FF7F00")) + 
  scale_y_continuous(expand =expansion(mult=c(0,0.05)), name = "Gene expression (FPKM)")
ggsave(here(fig_dir, "UCP1_RNA_expr.pdf"))
```


```{r}
ggplot(filter(long, gene_name == "MT-ATP8"), 
         aes(x=subject, y=fpkm, fill=condition)) +
    geom_bar(stat = "summary", fun=mean, position=position_dodge2(preserve="single"))  + 
    geom_beeswarm(dodge.width=0.9, cex=1.5) + 
    scale_fill_manual(values = c("#1F78B4","#FF7F00")) + 
  scale_y_continuous(expand =expansion(mult=c(0,0.05)), name = "Gene expression (FPKM)")
```





















