---
title: "monocle_umap_tss_fastmnn_analysis"
author: "Sarah Hazell Pickering"
date: "2024-09-19"
output: html_document
---

No loops.  

```{r params}
module="adipogenesis"
method_name="fastmnn"
dataname = paste0("tss_bvw_",method_name)

library(here); i_am(file.path("analysis", paste0(dataname,"_monocle_umap.Rmd")))

odir = here("output", module, dataname)

load_data = T #loading data 
subset_data = F
```


```{r libs, warning=F, message=F, echo=F}
library(dplyr)
library(ggplot2)
library(Seurat)
library(BPCells)
library(monocle3)
library(viridis)
```


```{r themes}
pal = c("#B3B3B3","#85C2EA","#B2DF8A","#1F78B4")
clusters = tvthemes::gravityFalls_pal()(13)
names(clusters) = 0:11
spectral = rev(RColorBrewer::brewer.pal(n = 11, name = "Spectral"))
		theme_hp = theme_classic(base_size=15) + 
		  theme(axis.line = element_line(linewidth = 0.25),
		        axis.ticks = element_line(linewidth=0.25),
		        strip.background = element_blank(), # remove boxes around facet labels
		        )
		#set for all ggplots
theme_set(theme_hp)
```

```{r}
if (subset_data){
  sbs = readRDS(here(odir, "10%_complete_analysis.rds"))
  Idents(sbs) = "seurat_clusters"
} else {
  sbs = readRDS(here(odir, "complete_analysis.rds"))
  DefaultAssay(sbs) = "RNA"
}
sbs
```

```{r}
head(sbs@meta.data) 

Idents(sbs) = "initial_clusters"
table(Idents(sbs))
sbs$seurat_clusters = sbs$initial_clusters
```

```{r}
DimPlot(sbs, reduction="umap") + scale_colour_manual(values=clusters)
```

## Convert to monocle object
```{r}
cds = SeuratWrappers::as.cell_data_set(sbs)
cds
```

```{r}
p= plot_cells(cds, show_trajectory_graph = F, cell_stroke=0.35, reduction_method = "UMAP", color_cells_by="seurat_clusters") + 
  scale_colour_manual(values=clusters)
p$layers[[1]]$aes_params$colour = 'transparent'
p
```

```{r}
cds = cluster_cells(cds)
p= plot_cells(cds, show_trajectory_graph = F, color_cells_by = "partition", label_cell_groups = F)
p$layers[[1]]$aes_params$colour = 'transparent'
p
```
Parition 2 is not even a separate cluster... Not sure what that is 

```{r}
cds = learn_graph(cds, close_loop = F)
p=plot_cells(cds, color_cells_by = "seurat_clusters",
           label_leaves=FALSE,
           label_branch_points=FALSE, cell_stroke=0.35,
           trajectory_graph_color = "black")+ 
  scale_colour_manual(values=clusters)
p$layers[[1]]$aes_params$colour = 'transparent'
p
```


## Order cells

```{r}
pick_root_node = function(cds,factor_name, start_bin){
  cell_ids = which(colData(cds)[,factor_name]==start_bin)
  closest_vertex <-  cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
  summary(closest_vertex)
  closest_vertex <- as.matrix(closest_vertex[colnames(cds), ])
  root_pr_nodes <- igraph::V(principal_graph(cds)[["UMAP"]])$name[as.numeric(names
    (which.max(table(closest_vertex[cell_ids,]))))]
return(root_pr_nodes)
}
pick_root_node(cds, "time","day0")
pick_root_node(cds, "time","day1")
pick_root_node(cds, "time","day3")
```



I suppose you can make your own, but not sure if it works through monocle.  
```{r}
cds = order_cells(cds, root_pr_nodes = pick_root_node(cds, "time", "day0"))
 plot_cells(cds, color_cells_by = "pseudotime", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="red") + scale_colour_viridis()
```


```{r}
cds = order_cells(cds, root_pr_nodes = pick_root_node(cds, "seurat_clusters", "6"))
plot_cells(cds, color_cells_by = "pseudotime", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="red") + scale_colour_viridis()
```

```{r}
cds = order_cells(cds, root_pr_nodes = pick_root_node(cds, "time", "day1"))
 plot_cells(cds, color_cells_by = "pseudotime", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="red") + scale_colour_viridis()
```

## Adipogenic end point
```{r}
cds = order_cells(cds, root_pr_nodes = pick_root_node(cds, "seurat_clusters", "5"))
p=plot_cells(cds, color_cells_by = "pseudotime", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="red") + scale_colour_viridis()
p$layers[[1]]$aes_params$colour = 'transparent'
p
```

## Save

```{r}
if (subset_data == FALSE){
  saveRDS(cds, here(odir,"monocle_complete_analysis_umap.rds"))
} else if (subset_data){ #if subset, don't save complete analysis
  saveRDS(cds, file =here(odir,"1%_monocle_subset_analysis_umap.rds") )
}
```

