---
title: "white_only_downsample_cluster_quality"
author: "Sarah Hazell Pickering"
date: "2026-01-07"
output: html_document
---



```{r libs, message=FALSE, warning=FALSE}
library(Seurat)
library(dplyr)
library(ggplot2)
library(here)
library(scSHC)
```

```{r params}
module = "adipogenesis"
dataname = "white_only_downsample"
load_data = T
subset_data = T

rmd_filename = "white_only_downsample"
i_am(file.path("analysis", module, paste0(rmd_filename,".Rmd")))
odir = here("output", module, dataname)
```


```{r setup}
set.seed(8)
fig_dir = here("analysis", module, "figures", rmd_filename)
if (!dir.exists(fig_dir)) dir.create(fig_dir, recursive = TRUE)
knitr::opts_chunk$set(fig.path = paste0(fig_dir, "/"),
                      dev = c("png","pdf"))

if (!dir.exists(odir)) dir.create(odir, recursive = TRUE)
```


```{r themes}
theme_hp = theme_classic(base_size = 15) +
  theme(axis.line = element_line(linewidth = 0.25),
        axis.ticks = element_line(linewidth = 0.25),
        strip.background = element_blank())
theme_set(theme_hp)
pal = c("#B3B3B3","#85C2EA","#B2DF8A","#1F78B4")
clusters = ggsci::pal_simpsons()(13)[c(1:7,9:13)]
spectral = rev(RColorBrewer::brewer.pal(n = 11, name = 'Spectral'))
```


## Read data

```{r}
if (subset_data){
  sbs = readRDS(here(odir, "10%_complete_analysis.rds"))
  Idents(sbs) = "seurat_clusters"
} else{
  sbs = readRDS(here(odir, "complete_analysis.rds"))
}
sbs
```

```{r}
DimPlot(sbs, cols = clusters)
```

### scSHC

```{r}
Idents(sbs) = "seurat_clusters"
tiny = subset(sbs, downsample=1000)
tiny
counts = as.matrix(tiny[["RNA"]]$counts)
counts[1:10,1:4]
```


```{r}
new_clusters = testClusters(counts, cluster_ids = as.character(tiny$seurat_clusters), 
                            #var.genes = VariableFeatures(tiny), 
                            parallel = F, cores = 1)
```


## new clusters
```{r}
table(new_clusters[[1]], tiny$seurat_clusters)
table(new_clusters[[1]], tiny$time)
```

```{r}
print(new_clusters[[2]])
```

```{r}
tiny$shc_clusters = new_clusters[[1]]
DimPlot(tiny, group.by="shc_clusters", cols=clusters)
```

```{r}
write.table(new_clusters[[2]], here(odir, "cluster_quality_summary.tsv"), row.names = F, quote = F)
```

