---
title: "figure7"
author: "Sarah Hazell Pickering"
date: "2026-03-04"
output: html_document
---

Add CXCL8 and ICAM UMAPs on adipogenesis
## Setup

```{r libs, message=FALSE, warning=FALSE}
library(BPCells)
library(Seurat)
library(ggplot2)
library(here)
library(tidyr)
library(dplyr)
```

```{r global_params}
load_data = T #loading data
subset_data = F

rmd_filename = "figure7_icam1"
i_am(file.path("figures", paste0(rmd_filename,".Rmd")))
```

```{r setup}
set.seed(8)
fig_dir = here("figures", rmd_filename)
if (!dir.exists(fig_dir)) dir.create(fig_dir, recursive = TRUE)
knitr::opts_chunk$set(fig.path = paste0(fig_dir, "/"),
                      dev = c("png","pdf"))
```


```{r themes}
theme_hp = theme_classic(base_size = 15) +
  theme(axis.line = element_line(linewidth = 0.25),
        axis.ticks = element_line(linewidth = 0.25),
        strip.background = element_blank())
theme_set(theme_hp)

spectral =  rev(RColorBrewer::brewer.pal(n = 11, name = "Spectral"))
```


# progenitor clusters 
```{r prog_setup}
module = "progenitors"
dataname="rpca"
odir = here("output", module, dataname)
prog_cols =   c("#DA1819","#691A93","#EBB400" , "#434D51","#00AED1","#3AAD00","#FF7F00","#AC8AD0")
```


```{r}
sbs = readRDS(here(odir, "complete_analysis.rds"))
```

```{r progenitors_rpca}
FeaturePlot(sbs, "ICAM1") + scale_colour_gradientn(colours=spectral)
FeaturePlot(sbs, "CXCL8") + scale_colour_gradientn(colours=spectral)
```


# Adipogenesis trajectories
```{r white_setup}
module = "adipogenesis"
dataname="white_only_downsample"
odir = here("output", module, dataname)
clusters =   ggsci::pal_simpsons()(12)[c(1:7,9:12)]
```

```{r}
sbs = readRDS(here(odir, "complete_analysis.rds"))
```

```{r white_only_adipogenesis}
FeaturePlot(sbs, "ICAM1", order=T) + scale_colour_gradientn(colours=spectral)
FeaturePlot(sbs, "CXCL8", order=T) + scale_colour_gradientn(colours=spectral)
```

# BVW level trajectories
```{r bvw_setup}
module = "beige_vs_white"
dataname="bvw_fastmnn"
odir = here("output", module, dataname)
clusters =   tvthemes::gravityFalls_pal()(13)
cluster_levels = as.character(c(7,11,1,10,3,8,9,0,5,6,2,4))
```

```{r}
sbs = readRDS(here(odir, "complete_analysis.rds"))
```


