---
title: "supp_S3_S4_progenitors"
author: "Sarah Hazell Pickering"
date: "2026-02-03"
output: html_document
---

# setup
```{r libs, message=FALSE, warning=FALSE}
library(Seurat)
library(clustree)
library(dplyr)
library(ggplot2)
library(here)
library(tidyr)
library(cowplot)
library(biomaRt)
```

```{r params}
module = "progenitors"
dataname = "integration_trial"
load_data = T #Loading initial seurat analysis
subset_data = F

rmd_filename = "supp_figS3_S4_progenitors"
i_am(file.path("figures", paste0(rmd_filename,".Rmd")))
odir = here("output", module, dataname)
```


```{r setup}
set.seed(8)
fig_dir = here("figures", rmd_filename)
if (!dir.exists(fig_dir)) dir.create(fig_dir, recursive = TRUE)
knitr::opts_chunk$set(fig.path = paste0(fig_dir, "/"),
                      dev = c("png","pdf"))

if (!dir.exists(odir)) dir.create(odir, recursive = TRUE)
```


```{r themes}
theme_hp = theme_classic(base_size = 15) +
  theme(axis.line = element_line(linewidth = 0.25),
        axis.ticks = element_line(linewidth = 0.25),
        strip.background = element_blank())
theme_set(theme_hp)
theme_zoom = theme_classic(30) &  
    theme(axis.line = element_line(linewidth = 0.5),
        axis.ticks = element_line(linewidth = 0.5),
        strip.background = element_blank()) 
pal = c("#0A7EA8","#EF5780","#0A8550","#1C31D3","#EE9614","#670F39")
clusters = c("#DA1819","#691A93","#EBB400" , "#434D51","#00AED1","#3AAD00","#FF7F00","#AC8AD0", tvthemes::gravityFalls_pal()(10))
spectral = rev(RColorBrewer::brewer.pal(n = 11, name = 'Spectral'))
```

# Supp FigS3 - Cluster resoltuions 
## Load Clustree info

```{r}
mult = readRDS(here(odir,"multiple_resolutions.rds"))
head(mult@meta.data)
table(mult$rpca_clusters)
```


```{r}
clustree(mult, prefix="res", suffix ="_clusters") + theme_void(base_size = 15) + theme_hp
```


```{r 3A_clustree}
clustree(mult, prefix="res", suffix ="_clusters", edge_width=1) + 
    theme_void(base_size = 15) + 
    scale_colour_manual(values=c("grey","grey","coral",rep("grey", 5)), guide = "none") + 
    geom_text(data=data.frame(res=c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8)), aes(x=-10.5, y=8-(res*10), label=res,)) +
    geom_text(data=data.frame("1"=1), aes(x=-10,y=7.75, label="Clustering\nresolution")) +
    scale_size(name = "Cells (k)", range = c(5,12), labels=function(x) paste(x/1000, "k"), breaks=c(1000,10000,20000),
               guide = guide_legend(order=1)) +
    scale_edge_alpha(name="Prop.\nshared cells") + 
    scale_edge_colour_gradientn(colours = c("black"), guide="none")
```

```{r}
DimPlot(mult, group.by = c("res0.2_clusters","res0.3_clusters","res0.5_clusters","res0.8_clusters"),
        pt.size =  0.1, shuffle=T) & theme_hp
```

```{r 3b_umaps}
Idents(mult) = "rpca_clusters"
DimPlot(mult, group.by = c("res0.2_clusters","res0.3_clusters","res0.5_clusters","res0.8_clusters"),
        pt.size =  0.1, alpha = 0.5, shuffle=T) & theme_classic(base_size = 12) &
  theme(axis.line = element_line(linewidth = 0.25),
        axis.ticks = element_line(linewidth = 0.25),
        strip.background = element_blank(),
        plot.title = element_text(size=12)
        )

```

# Supp FigS4 - Cell cycle

## load data

```{r s4_params}
dataname="rpca"
odir = here("output", module, dataname)
```


```{r}
if (subset_data){
  filt = readRDS(here(odir, "10%_complete_analysis.rds"))
} else{
  filt = readRDS(here(odir, "complete_analysis.rds"))
}
filt
```


```{r}
cc_file <- "https://raw.githubusercontent.com/hbc/tinyatlas/master/cell_cycle/Homo_sapiens.csv"
cell_cycle_genes <- read.csv(cc_file)
head(cell_cycle_genes)
table(cell_cycle_genes$phase)
```


```{r}
mart <- biomaRt::useMart(biomart = "ensembl",
  dataset = "hsapiens_gene_ensembl",
  host = "https://apr2020.archive.ensembl.org") #ensembl98 no longer available 99 closest
annot = biomaRt::getBM(c("external_gene_name", "description", "ensembl_gene_id", "gene_biotype"), 
              filters = "ensembl_gene_id",
              values = as.character(cell_cycle_genes$geneID),
              mart = mart,
              useCache = F)
annot$description = gsub("\\[.*\\]", "", annot$description)
head(annot)
cell_cycle_genes = merge(cell_cycle_genes, annot, by.x="geneID", by.y="ensembl_gene_id")
head(cell_cycle_genes)
write.table(here("data/gene_sets/cell_cycle_genes_ensembl.tsv"))
```

## Cell cycle scoring
```{r}
filt <- CellCycleScoring(filt,
                      g2m.features = cell_cycle_genes$external_gene_name[cell_cycle_genes$phase == "G2/M"],
                      s.features = cell_cycle_genes$external_gene_name[cell_cycle_genes$phase == "S"])
summary(filt$G2M.Score)
```

## S4A Phase UMAP
```{r 4Ascore_UMAP}
phase_plots = FeaturePlot(filt, features=c( "G2M.Score","S.Score"), blend=T, ncol=2, combine=F, pt.size=0.5) 
phase_plots[[3]] & theme_hp & theme(legend.position="none") & labs(title=NULL)
phase_plots[[4]] & theme_zoom & labs(title=NULL)
```

## S4B
```{r 4Bvlnplot}
VlnPlot(filt, features=c("G2M.Score", "S.Score"), group.by="rpca_clusters", cols=clusters, pt.size = 0) & 
    theme_hp & scale_x_discrete(name = "Progenitor cluster", label=function(x) paste0("p",x)) &
    scale_fill_manual(values=clusters, guide="none") &
    labs( y="Average expression score")
```

## S4C - Score scatter plots

```{r 4C_main_phasescatter}
FeatureScatter(filt, feature1="G2M.Score", feature2="S.Score", group.by="rpca_clusters", cols=clusters, pt.size=0.75)+ 
    theme_hp + labs(title=NULL) + 
    scale_colour_manual(values=clusters, name="Progenitor\ncluster", label = function(x) paste0("p",x),
                        guide = guide_legend(override.aes = list(size=3)))
    
```

```{r 4C_inset_umap}
DimPlot(filt, cols=clusters) + 
    theme_hp + scale_colour_manual(values=clusters, name="Progenitor\ncluster", label = function(x) paste0("p",x))
DimPlot(filt, cols=clusters, pt.size=0.75) + coord_cartesian(x=c(2,9),y=c(-6,1))+
    theme_zoom + scale_colour_manual(values=clusters ,guide="none")
```

```{r }
ggplot(filt@meta.data) + geom_point(aes(x=G2M.Score, y=S.Score, colour=rpca_clusters))
```


## S4D Proportion plot

```{r composition}
composition = read.delim(here(odir, "cluster_composition.txt"))
composition$seurat_clusters = factor(composition$seurat_clusters, levels=c(0,1:max(composition$seurat_clusters)))
head(composition)

clu_to_plot = c(4,5)
```


```{r Dproportion}
ggplot(filter(composition, seurat_clusters %in% clu_to_plot)) + 
  geom_bar(stat="identity",aes(x=donor_id, y=cells_per_donor, fill=seurat_clusters)) + 
  scale_y_continuous(expand = expansion(mult=c(0, 0.05)))+ 
   scale_fill_manual(values=clusters[clu_to_plot+1], labels=function(x) paste0("p", x)) +
    labs(x="Subject", y="Proportion of cells", fill="Progenitor\nclusters")
```


