---
title: "tables_supplemental"
author: "Sarah Hazell Pickering"
date: "2026-03-04"
output: html_document
---


```{r}
library(writexl)
library(here)
library(dplyr)
i_am("figures/tables_supplemental.Rmd")
```


```{r}
input_tables = data.frame(
    number = c(2:9),
    name = c("Progenitor subject GO","progenitor RPCA genes","Progenitor rpca GOterms",
               "Adipogenesis genes",
               "Beige vs white DEGs","TSS_DE_per_cluster","G2G alignment TSSs","G2G alignment genes"),
    module = c(rep("progenitors", 3), "adipogenesis",rep("beige_vs_white", 4)),
    dataname = c("initial",rep("rpca",2),
                 "white_only_downsample",
                 "downsample","tss_bvw_initial", "tss_fastmnn", "bvw_fastmnn"),
    file = c("ORA_donor_marker_genes.txt","marker_genes.txt", "ORA_marker_genes.txt","marker_genes.txt",
             "DE_per_cluster_white_vs_beige.tsv","DE_per_cluster_wvb.tsv", "g2g_alignment_genes.tsv","g2g_alignment_genes.tsv")
    
)
input_tables
cat(paste("\"output",sep="/",input_tables$module, input_tables$dataname, paste0(input_tables$file,"\",")))
```

```{r}
table_list <- list()
for (i in seq_len(nrow(input_tables))) {
    row <- input_tables[i, ]
    sheet_name <- substr(paste0("Table_S",row$number, "_",row$name), 1, 31)
    table = read.delim(  here("output", row$module, row$dataname, row$file))
    if (grepl("ORA", row$file)){
        table$Description = NULL
    } else if (grepl("TSS_DE", row$name)){
        table = select(table, cluster, p_val, avg_log2FC, pct.1,pct.2,p_val_adj,tss_id,gene_names,proximity,condition,time)
    }
    table_list[[sheet_name]] <- table
}
write_xlsx(table_list, path = here("figures/tables_supplemental.xlsx"), format_headers = TRUE)
```

