---
title: "bvw_fastmnn_monocle_umap_plots"
author: "Sarah Hazell Pickering"
date: "2025-03-12"
output: html_document
---

## Setup

```{r params}
module="adipogenesis"
method_name="fastmnn"
dataname = paste0("tss_bvw_",method_name)

library(here); i_am(file.path("analysis", paste0(dataname,"_monocle_umap.Rmd")))

odir = here("output", module, dataname)

load_data = T #loading data 
subset_data = F
```

```{r libs, warning=F, message=F, echo=F}
library(dplyr)
library(ggplot2)
library(Seurat)
library(BPCells)
library(monocle3)
library(viridis)
```


```{r themes}
pal = c("#B3B3B3","#85C2EA","#1F78B4")
prog_cols = c("#DA1819","#691A93","#EBB400" , "#434D51","#00AED1","#3AAD00","#FF7F00","#AC8AD0")
clusters = tvthemes::gravityFalls_pal()(13)
names(clusters) = 0:11
spectral = rev(RColorBrewer::brewer.pal(n = 11, name = "Spectral"))
theme_hp = theme_classic(base_size=15) + 
		  theme(axis.line = element_line(linewidth = 0.25),
		        axis.ticks = element_line(linewidth=0.25),
		        strip.background = element_blank(), # remove boxes around facet labels
		        )
theme_set(theme_hp)
knitr::opts_chunk$set(dev=c("png","pdf"))
```

```{r}
beige =  readRDS(here(odir,"beige_monocle_complete_analysis_umap.rds"))
white = readRDS(here(odir,"white_monocle_complete_analysis_umap.rds"))
beige
colnames(colData(beige))
```

```{r}
table(beige$time.progen_clusters)
```


```{r beige_trajectories}
p=plot_cells(beige, color_cells_by = "time.progen_clusters", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F,  cell_size=0.5)+
  scale_colour_manual(values=c(prog_cols, pal))
p$layers[[1]]$aes_params$colour = 'transparent' 
p


p=plot_cells(beige, color_cells_by = "time.progen_clusters", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F,  cell_size=0.2)+
  scale_colour_manual(values=c(prog_cols, pal))
p$layers[[1]]$aes_params$colour = 'transparent'
p + facet_wrap(~ time.progen_clusters)
```

```{r white_trajectories}
w=plot_cells(white, color_cells_by = "time.progen_clusters", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F,  cell_size=0.5) +
  scale_colour_manual(values=c(prog_cols, pal),name = "cluster")
w$layers[[1]]$aes_params$colour = 'transparent'
w


w=plot_cells(white, color_cells_by = "time.progen_clusters", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F, cell_size=0.2) +
  scale_colour_manual(values=c(prog_cols, pal),name = "cluster")
w$layers[[1]]$aes_params$colour = 'transparent'
w + facet_wrap(~ time.progen_clusters)
```


```{r white_prog_trajectories}
white_progen = white[,subset(colData(white), grepl("^p[0-7]",time.progen_clusters)) %>%row.names]
w=plot_cells(white_progen, color_cells_by = "time.progen_clusters", label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F, cell_size=0.2)
w$layers[[1]]$aes_params$colour = 'transparent'
w + facet_wrap(~ time.progen_clusters) +
  scale_colour_manual(values=c(prog_cols, pal),name = "cluster")
```

```{r only_graph_white}
plot_cells(white, label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F, cell_size=0)
```

```{r only_graph_beige}
plot_cells(beige, label_leaves = F, label_branch_points = F, 
                trajectory_graph_color="black", label_cell_groups = F, cell_size=0)
```


## Violin plot of velocity
```{r}
if (subset_data){
  sbs = readRDS(here(odir, "10%_complete_analysis.rds"))
  Idents(sbs) = "seurat_clusters"
} else {
  sbs = readRDS(here(odir, "complete_analysis.rds"))
  DefaultAssay(sbs) = "RNA"
}
sbs
```


```{r}
Idents(sbs) = "sample"
sbs_white = subset(sbs, idents=c("asc_day0", "white_day1","white_day3"))
summary(colnames(white) == rownames(sbs_white@meta.data))
sbs_white$raw_pseudotime = pseudotime(white)
sbs_white$monocle_pseudotime =   scales::rescale(pseudotime(white), to = c(1, 0)) #rescale from 1 to 0 (cos were tracing backwards from  day3)
sbs_white$pscondition ="white"

sbs_beige = subset(sbs, idents=c("asc_day0", "beige_day1","beige_day3"))
summary(colnames(beige) == rownames(sbs_beige@meta.data))
sbs_beige$raw_pseudotime = pseudotime(beige)
sbs_beige$monocle_pseudotime =   scales::rescale(sbs_beige$raw_pseudotime, to = c(1, 0)) #rescale from 1 to 0 (cos were tracing backwards from  day3)
sbs_beige$pscondition ="beige"
```

```{r }
merged_obj <- merge(x = sbs_white, y = sbs_beige, add.cell.ids = c("white","beige"), merge.dr = F)
merged_obj
merged_obj$time.progen_clusters = factor(merged_obj$time.progen_clusters, levels=c(paste0("p",0:7),paste0("day",c(0,1,3))))
```

```{r paired_ridge_plot}
VlnPlot(merged_obj, features = "monocle_pseudotime", group.by = "time.progen_clusters", split.by="pscondition",
        cols= c( "#FF7F00","#1F78B4"), pt.size = 0, split.plot = T) +
  scale_x_discrete(limits = c(paste0("p",c(5,6,7,0,3,4,2,1)), paste0("day",c(0,1,3)))) +
  ylab("Pseudotime")


VlnPlot(merged_obj, features = "raw_pseudotime", group.by = "time.progen_clusters", split.by="pscondition",
        cols= c( "#FF7F00","#1F78B4"), pt.size = 0, split.plot = T) +
  scale_x_discrete(limits = c(paste0("p",c(5,6,7,0,3,4,2,1)), paste0("day",c(0,1,3)))) +
  ylab("Pseudotime")
VlnPlot(merged_obj, features = "monocle_pseudotime", group.by = "time.progen_clusters",split.by="pscondition",
        cols= c( "#FF7F00","#1F78B4"), pt.size = 0) +
  scale_x_discrete(limits = c(paste0("p",c(5,6,7,0,3,4,2,1)), paste0("day",c(0,1,3)))) +
  ylab("Pseudotime") 
```


```{r}
VlnPlot(sbs_white, features = "monocle_pseudotime", group.by = "time.progen_clusters", cols=c(prog_cols, pal), pt.size = 0) +
  scale_x_discrete(limits=c(paste0("p",c(5,6,7,0,3,4,2,1)), paste0("day",c(0,1,3))))
RidgePlot(sbs_white, features = "monocle_pseudotime", group.by = "time.progen_clusters", cols=c(prog_cols, pal)) +
  scale_y_discrete(limits=c(paste0("p",c(5,6,7,0,3,4,2,1)), paste0("day",c(0,1,3))))
```


```{r}
VlnPlot(sbs_beige, features = "monocle_pseudotime", group.by = "time.progen_clusters", cols=c(prog_cols, pal), pt.size = 0) +
  scale_x_discrete(limits=c(paste0("p",c(5,6,7,0,3,4,2,1)), paste0("day",c(0,1,3))))
RidgePlot(sbs_beige, features = "monocle_pseudotime", group.by = "time.progen_clusters", cols=c(prog_cols, pal)) +
  scale_y_discrete(limits=c(paste0("p",c(5,6,7,0,3,4,2,1)), paste0("day",c(0,1,3))))
```


```{r}
meta_white = sbs_white@meta.data %>% mutate(pscondition = "white")
meta_beige = sbs_beige@meta.data %>% mutate(pscondition = "beige")
meta = rbind(meta_white, meta_beige)
str(meta)
table(meta$pscondition)


ggplot(meta, aes(y=monocle_pseudotime, x=time.progen_clusters, fill=time.progen_clusters)) + geom_boxplot() +
  facet_grid(pscondition~.) + scale_fill_manual(values=c(prog_cols, pal))

ggplot(meta, aes(y=monocle_pseudotime, x=time.progen_clusters, fill=time.progen_clusters)) + geom_violin(scale="width")+
  facet_grid(pscondition~.) + scale_fill_manual(values=c(prog_cols, pal), name="identity") + 
  scale_x_discrete(limits=c(paste0("p",c(5,6,7,0,3,4,2,1)), paste0("day",c(0,1,3))))
```


