---
title: "White only integration trial"
output: html_document
---

Integrate white adipogenesis using RPCA, FastMNN and Harmony

```{r params}
module="adipogenesis"
dataname = "white_only_integration_trial"

library(here); i_am(file.path("analysis",paste0(dataname, ".Rmd")))
odir = here("output", module, dataname) 
indir = here("output", module, "white_only_downsample")
load_data = T #loading data 
subset_data = F

if (!dir.exists(here(odir))){dir.create(here(odir), recursive = T)}
```


```{r libs, warning=F, message=F, echo=F}
library(dplyr)
library(ggplot2)
library(ggsci)

library(Seurat)
library(SeuratWrappers)
library(BPCells)
library(patchwork)
```


```{r themes}
pal = c("#B3B3B3","#85C2EA","#B2DF8A","#1F78B4")
clusters = ggsci::pal_simpsons()(13)[c(1:7,9:13)]

theme_hp = theme_classic(base_size=15) + 
		  theme(axis.line = element_line(linewidth = 0.25),
		        axis.ticks = element_line(linewidth=0.25),
		        strip.background = element_blank(), # remove boxes around facet labels
		        )

theme_set(theme_hp)
knitr::opts_chunk$set(dev=c('png','pdf'))
```

## Read data

```{r}
if (subset_data){
  sbs = readRDS(here(indir, "10%_complete_analysis.rds"))
  Idents(sbs) = "seurat_clusters"
} else {
  sbs = readRDS(here(indir, "complete_analysis.rds"))
  DefaultAssay(sbs) = "RNA"
}
sbs[["RNA"]] =split(sbs[["RNA"]], f = sbs$orig.ident)
sbs
```


```{r}
sbs$initial_clusters = sbs$seurat_clusters
sbs[["initial.umap"]] = sbs[["umap"]]
sbs[["initial.tsne"]] = sbs[["tsne"]]
```

```{r}
DimPlot(sbs, cols=clusters, label=T)
```


## RPCA Integration

```{r setup-variables-rpca}
method_name="rpca"
red_name = paste("pca", sep=".", method_name)
umap_name = paste("umap", sep=".", method_name)
clu_name = paste( method_name, sep="_", "clusters")
tsne_name = paste("tsne", sep=".", method_name)
```

```{r}
sbs = IntegrateLayers(sbs, method= RPCAIntegration, orig.reduction = "pca",
                       new.reduction = red_name, 
                      assay = "RNA", scale.layer="scale.data", layers="data"
                      )
```

```{r basic_analysis}
sbs <- FindNeighbors(sbs, reduction =  red_name, dims = 1:20, verbose=F)
sbs <- FindClusters(sbs, resolution = 0.5, cluster.name =  clu_name)
sbs <- RunUMAP(sbs, reduction = red_name, dims = 1:20, reduction.name = umap_name)
```

```{r}
DimPlot(sbs, reduction = umap_name,  group.by = clu_name, label=T, cols=clusters) + theme_hp
DimPlot(sbs, reduction = umap_name,  group.by = "orig.ident", cols=pal)+ theme_hp
DimPlot(sbs, reduction = umap_name,  group.by = "initial_clusters", label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = "initial.umap",  group.by = clu_name, label=T, cols=clusters)+ theme_hp
```

```{r}
sbs = RunTSNE(sbs, reduction = red_name, dims = 1:20, reduction.name = tsne_name)
```

```{r}
DimPlot(sbs, reduction = tsne_name,  group.by = clu_name, label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = tsne_name,  group.by = "orig.ident", cols=pal)+ theme_hp
DimPlot(sbs, reduction = tsne_name,  group.by = "initial_clusters", label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = "initial.tsne",  group.by = clu_name, label=T, cols=clusters)+ theme_hp
```

## Harmony Integration

```{r setup-variables-harmony}
method_name="harmony"
red_name = paste("pca", sep=".", method_name)
umap_name = paste("umap", sep=".", method_name)
clu_name = paste( method_name, sep="_", "clusters")
tsne_name = paste("tsne", sep=".", method_name)
```

```{r}
sbs = IntegrateLayers(sbs, method= HarmonyIntegration, orig.reduction = "pca",
                       new.reduction = red_name)
```

```{r}
sbs <- FindNeighbors(sbs, reduction =  red_name, dims = 1:20, verbose=F)
sbs <- FindClusters(sbs, resolution = 0.5, cluster.name =  clu_name)
sbs <- RunUMAP(sbs, reduction = red_name, dims = 1:20, reduction.name = umap_name)
```


```{r}
DimPlot(sbs, reduction = umap_name,  group.by = clu_name, label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = umap_name,  group.by = "orig.ident", cols=pal)+ theme_hp
DimPlot(sbs, reduction = umap_name,  group.by = "initial_clusters", label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = "initial.umap",  group.by = clu_name, label=T, cols=clusters)+ theme_hp
```

```{r}
sbs = RunTSNE(sbs, reduction = red_name, dims = 1:20, reduction.name = tsne_name)
```

```{r}
DimPlot(sbs, reduction = tsne_name,  group.by = clu_name, label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = tsne_name,  group.by = "orig.ident", cols=pal)+ theme_hp
DimPlot(sbs, reduction = tsne_name,  group.by = "initial_clusters", label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = "initial.tsne",  group.by = clu_name, label=T, cols=clusters)+ theme_hp
```

## FastMNN

```{r setup-variables-fastmnn}
method_name="fastmnn"
red_name = paste("pca", sep=".", method_name)
umap_name = paste("umap", sep=".", method_name)
clu_name = paste( method_name, sep="_", "clusters")
tsne_name = paste("tsne", sep=".", method_name)
```

```{r}
sbs = IntegrateLayers(sbs, method= FastMNNIntegration, orig.reduction = "pca",
                       new.reduction = red_name)
```

```{r}
sbs <- FindNeighbors(sbs, reduction =  red_name, dims = 1:20, verbose=F)
sbs <- FindClusters(sbs, resolution = 0.5, cluster.name =  clu_name)
sbs <- RunUMAP(sbs, reduction = red_name, dims = 1:20, reduction.name = umap_name)
```


```{r}
DimPlot(sbs, reduction = umap_name,  group.by = clu_name, label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = umap_name,  group.by = "orig.ident", cols=pal)+ theme_hp
DimPlot(sbs, reduction = umap_name,  group.by = "initial_clusters", label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = "initial.umap",  group.by = clu_name, label=T, cols=clusters)+ theme_hp
```

```{r}
sbs = RunTSNE(sbs, reduction = red_name, dims = 1:20, reduction.name = tsne_name)
```

```{r}
DimPlot(sbs, reduction = tsne_name,  group.by = clu_name, label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = tsne_name,  group.by = "orig.ident", cols=pal)+ theme_hp
DimPlot(sbs, reduction = tsne_name,  group.by = "initial_clusters", label=T, cols=clusters)+ theme_hp
DimPlot(sbs, reduction = "initial.tsne",  group.by = clu_name, label=T, cols=clusters)+ theme_hp
```

```{r save}
if (subset_data == FALSE){
  saveRDS(sbs, file = here(odir, "complete_analysis.rds"))
  sub = subset(sbs, downsample=1000)
  saveRDS(sub,here(odir, "10%_complete_analysis.rds"))
} else if (subset_data){ #if subset, don't save complete analysis
  saveRDS(sbs,here(odir, "10%_subset_analysis.rds"))
}
```
